prompt Creating package pdao_insert...
@@PDAO_INSERT.sql;
prompt Creating package pdao_update...
@@PDAO_UPDATE.sql;
prompt Creating package pdao_findby_pk...
@@PDAO_FINDBY_PK.sql;
prompt Creating package pdao_findby_uk...
@@PDAO_FINDBY_UK.sql;
prompt Creating package PBO_ACC...
@@PBO_ACC.sql;
prompt Creating package PBO_BPARTNER...
@@PBO_BPARTNER.sql;
prompt Creating package PBO_CLIENT...
@@PBO_CLIENT.sql;
prompt Creating package PBO_IINV...
@@PBO_IINV.sql;
prompt Creating package PBO_ORG...
@@PBO_ORG.sql;
prompt Creating package PBO_PARCEL...
@@PBO_PARCEL.sql;
prompt Creating package PBO_PRICE...
@@PBO_PRICE.sql;
prompt Creating package PBO_PRODUCT...
@@PBO_PRODUCT.sql;
prompt Creating package PBO_RINV...
@@PBO_RINV.sql;
prompt Creating package PBO_STOCK...
@@PBO_STOCK.sql;
prompt Creating package PBO_TRANSP...
@@PBO_TRANSP.sql;
prompt Creating package PBO_UOM...
@@PBO_UOM.sql;
prompt Creating package PK_CLIENT...
@@PK_CLIENT.sql;
prompt Creating package PK_PAYMENT...
@@PK_PAYMENT.sql;
prompt Creating package PK_SESSION...
@@PK_SESSION.sql;
prompt Creating package PK_SYSTEM...
@@PK_SYSTEM.sql;
prompt Creating package PS_ACC...
@@PS_ACC.sql;
prompt Creating package PS_IMPEX...
@@PS_IMPEX.sql;
prompt Creating package PS_UTIL...
@@PS_UTIL.sql;
prompt Creating package X_IMP...
@@X_IMP.sql;
