prompt Creating package pdao_insert...
@@PDAO_INSERT.sql;
prompt Creating package pdao_update...
@@PDAO_UPDATE.sql;
prompt Creating package pdao_findby_pk...
@@PDAO_FINDBY_PK.sql;
prompt Creating package pdao_findby_uk...
@@PDAO_FINDBY_UK.sql;
 