N21.DataComp.DC0016.prototype.resourceBundle =  {
DcProperty:{ 
  Title:"Parcel master-data"
    }
,FieldLabel:{ 
      EXP_ZIP:"Sender zip"
     ,EXP_ADRESS_NOTE:"Sender adress note"
     ,DEST_BPARTNER_ID:"Receiver ID"
     ,DEST_NAME:"Receiver name"
     ,DEST_BPADRESS_ID:"Receiver adress ID"
     ,DEST_BPADRESS:"Receiver adress"
     ,DEST_COUNTRY:"Receiver country"
     ,DEST_REGION:"Receiver region"
     ,DEST_CITY:"Receiver city"
     ,DEST_CITY_ID:"Receiver city ID"
     ,DEST_ZIP:"Receiver zip"
     ,DEST_ADRESS_NOTE:"Receiver adress notes"
     ,PICKEDUP:"Picked-up"
     ,PICKUP_MODE:"Pickup mode"
     ,PICKUP_DATE:"Pickup date"
     ,PICKUP_AGENT_NAME:"Pickup agent"
     ,DELIVERED:"Delivered"
     ,DELIVERY_MODE:"Delivery mode"
     ,DELIVERY_DATE:"Delivery date"
     ,DELIVERY_AGENT_NAME:"Delivery agent"
     ,DELIVERED_TO_NAME:"Deliv. to person"
     ,DELIVERED_TO_IDENT:"Deliv. to pers. ident"
     ,REJECTED:"Rejected"
     ,REJECT_DATE:"Reject date"
     ,REJECT_REASON:"Reject reason"
     ,REJECTED_BY_NAME:"Rej. by pers"
     ,REJECTED_BY_IDENT:"Rej. by pers ident"
     ,PACKAGE_COUNT:"Package count"
     ,CONTENT:"Content"
     ,CLIENT_CODE:"Client"
     ,NOTES:"Notes"
     ,DECLARED_VALUE:"Declared value"
     ,INSURED_VALUE:"Insured value"
     ,REF_PARCEL_ID:"Ref parcel ID"
     ,REF_PARCEL_REFERENCE_TYPE:"Ref_parcel_reference_type"
     ,CREATEDON:"Created on"
     ,CREATEDBY:"Created by"
     ,MODIFIEDBY:"Modified by"
     ,ID:"ID"
     ,CODE:"Code"
     ,CLIENT_ID:"Client ID"
     ,EXP_BPARTNER_ID:"Sender ID"
     ,EXP_NAME:"Sender name"
     ,EXP_BPADRESS_ID:"Sender adress ID"
     ,EXP_BPADRESS:"Sender adress"
     ,EXP_COUNTRY:"Sender country"
     ,EXP_REGION:"Sender region"
     ,EXP_CITY:"Sender city"
     ,EXP_CITY_ID:"Sender city ID"
     ,MODIFIEDON:"Modified on"
     ,REJECT_REASON_CODE:"Reject reason type"
     ,PICKUP_AGENT_ID:"Pickup agent ID"
     ,DELIVERY_AGENT_ID:"Delivery agent ID"
     ,CUSTODY_ORG_ID:"In inventory ID"
     ,CUSTODY_ORG_NAME:"In inventory"
     ,LAST_EVENT_ID:""
     ,LAST_EVENT_NAME:"Last event"
    }
,FieldsetTitle:{ 
      Delivery:"Delivery"
     ,Notes:"Notes"
     ,ParcelInfo:"ParcelInfo"
     ,Pickup:"Pickup"
     ,Receiver:"Receiver"
     ,Return:"Return"
     ,Sender:"Sender"
     ,Status:"Status"
    }
  }
N21.DataComp.DC0016G.prototype.resourceBundle = N21.DataComp.DC0016.prototype.resourceBundle;
N21.DataComp.DC0016F.prototype.resourceBundle = N21.DataComp.DC0016.prototype.resourceBundle;

