prompt Creating package PBO_CLIENT...
@@PBO_CLIENT.sql;
prompt Creating package PBO_ORG...
@@PBO_ORG.sql;
prompt Creating package PBO_PRICE...
@@PBO_PRICE.sql;
prompt Creating package PBO_PRODUCT...
@@PBO_PRODUCT.sql;
prompt Creating package PBO_RINV...
@@PBO_RINV.sql;
prompt Creating package PBO_STOCK...
@@PBO_STOCK.sql;
prompt Creating package PBO_UOM...
@@PBO_UOM.sql;
prompt Creating package PK_ACC...
@@PK_ACC.sql;
prompt Creating package PK_CLIENT...
@@PK_CLIENT.sql;
prompt Creating package PK_IINV...
@@PK_IINV.sql;
prompt Creating package PK_PAYMENT...
@@PK_PAYMENT.sql;
prompt Creating package PK_RINV...
@@PK_RINV.sql;
prompt Creating package PK_SESSION...
@@PK_SESSION.sql;
prompt Creating package PK_SYSTEM...
@@PK_SYSTEM.sql;
prompt Creating package X_IMP...
@@X_IMP.sql;
