prompt Creating package pdao_insert...
@@pdao_insert.sql;
prompt Creating package pdao_update...
@@pdao_update.sql;
prompt Creating package pdao_findby_pk...
@@pdao_findby_pk.sql;
prompt Creating package pdao_findby_uk...
@@pdao_findby_uk.sql;