-- Create the user
set echo on
set verify off

create user &1. identified by &2
  default tablespace USERS
  temporary tablespace TEMP
  profile DEFAULT;

GRANT CONNECT, RESOURCE TO &1;

GRANT CREATE TABLE TO &1;
GRANT CREATE TRIGGER TO &1;
GRANT CREATE SESSION TO &1;
GRANT CREATE ROLLBACK SEGMENT TO &1;
GRANT CREATE JOB TO &1;
GRANT CREATE SEQUENCE TO &1;
GRANT CREATE TYPE TO &1;
GRANT CREATE VIEW TO &1;
GRANT CREATE PROCEDURE TO &1;
GRANT DEBUG CONNECT SESSION TO &1;
exit;