prompt Creating package ps_ie...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
create or replace package ps_ie is                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
end;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
show errors package ps_ie;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
create or replace package body ps_ie is                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  function prepare_statement(p_imp_strategy_id in number) return varchar2 is                                                                                                                                                                                                                                                                                                                                                                                                                                        
    vr_strartegy ie_imp_strategy%rowtype;                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  begin                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
    pdao_findby_pk.ie_imp_strategy_t(p_imp_strategy_id,vr_strartegy,'Y');                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  end;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  /**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
   *  Run import: transfer data loaded by the import strategy loader from the temporary load table into target table                                                                                                                                                                                                                                                                                                                                                                                                
   *  according to bussiness rules defined by the import strategy                                                                                                                                                                                                                                                                                                                                                                                                                                                   
   */                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
  procedure run_import(p_import_id in number) is                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
    cursor c is                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
      select * from ie_import_data t                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
       where t.import_id = p_import_id;                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
  begin                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
    for r in c loop                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
      null;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
    end loop;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  end;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  /**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
   *  Run import strategy: Load data from the file to be imported into the temporary table.                                                                                                                                                                                                                                                                                                                                                                                                                         
   *  according to bussiness rules defined by the import strategy                                                                                                                                                                                                                                                                                                                                                                                                                                                   
   */                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
  procedure run_imp_strategy(p_imp_strategy_id in number) is                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  begin                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
   null;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
  end;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
end;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
/                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
show errors package body ps_ie;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
