prompt Creating table ACCOUNT...

CREATE TABLE ACCOUNT (
   ID             NUMBER(1)  NOT NULL
  ,CLIENT_ID      NUMBER(1)  NOT NULL
  ,ACCOUNT        VARCHAR2(1)  NOT NULL
  ,NAME           VARCHAR2(1)  NOT NULL
  ,SUMMARY        CHAR(1)
  ,PARENT_ACCOUNT VARCHAR2(1) 
  ,CURRENCY       VARCHAR2(1) 
  ,DESCRIPTION    VARCHAR2(1) 
  ,ACTIVE         CHAR(1) NOT NULL
  ,CREATEDON      DATE NOT NULL
  ,CREATEDBY      VARCHAR2(1)  NOT NULL
  ,MODIFIEDON     DATE NOT NULL
  ,MODIFIEDBY     VARCHAR2(1)  NOT NULL
  ,ACCJOURNAL_ID  NUMBER(1) 
  ,ACCGRP_ID      NUMBER(1) 
  ,ACCSCHEMA_ID   NUMBER(1)  NOT NULL
);
ALTER TABLE ACCOUNT ADD CONSTRAINT PK_ACCOUNT PRIMARY KEY (ID);
ALTER TABLE ACCOUNT ADD CONSTRAINT UK_ACCOUNT UNIQUE (CLIENT_ID,ACCOUNT);

prompt Creating table ACCOUNTING_DOC...

CREATE TABLE ACCOUNTING_DOC (
   ID             NUMBER(1)  NOT NULL
  ,CLIENT_ID      NUMBER(1)  NOT NULL
  ,ACCPERIOD_NAME VARCHAR2(1)  NOT NULL
  ,DOC_NO         NUMBER(1)  NOT NULL
  ,DOC_DATE       DATE NOT NULL
  ,BASEDOC_TYPE   VARCHAR2(1) 
  ,BASEDOC_NO     VARCHAR2(1) 
  ,BASEDOC_DATE   DATE
  ,BASEDOC_ID     NUMBER(1) 
  ,NOTES          VARCHAR2(1) 
  ,IS_GENERATED   CHAR(1) NOT NULL
  ,IS_INSERTED    CHAR(1) NOT NULL
  ,IS_POSTED      CHAR(1) NOT NULL
  ,CREATEDON      DATE NOT NULL
  ,CREATEDBY      VARCHAR2(1)  NOT NULL
  ,MODIFIEDON     DATE NOT NULL
  ,MODIFIEDBY     VARCHAR2(1)  NOT NULL
  ,POSTEDON       DATE
  ,POSTEDBY       VARCHAR2(1) 
);
ALTER TABLE ACCOUNTING_DOC ADD CONSTRAINT PK_ACCDOC PRIMARY KEY (ID);

prompt Creating table ACCOUNTING_DOC_LINE...

CREATE TABLE ACCOUNTING_DOC_LINE (
   ID            NUMBER(1)  NOT NULL
  ,ACCDOC_ID     NUMBER(1)  NOT NULL
  ,CLIENT_ID     NUMBER(1)  NOT NULL
  ,DB_ACCT       VARCHAR2(1) 
  ,CR_ACCT       VARCHAR2(1) 
  ,DB_AMOUNT     NUMBER(1)  NOT NULL
  ,CR_AMOUNT     NUMBER(1)  NOT NULL
  ,CURRENCY      VARCHAR2(1)  NOT NULL
  ,CREATEDON     DATE NOT NULL
  ,CREATEDBY     VARCHAR2(1)  NOT NULL
  ,MODIFIEDON    DATE NOT NULL
  ,MODIFIEDBY    VARCHAR2(1)  NOT NULL
  ,NOTES         VARCHAR2(1) 
  ,IS_GENERATED  CHAR(1) NOT NULL
  ,ORIG_AMOUNT   NUMBER(1) 
  ,ORIG_CURRENCY VARCHAR2(1) 
  ,XRATE         NUMBER(1) 
);
ALTER TABLE ACCOUNTING_DOC_LINE ADD CONSTRAINT PK_ACCDOCLIN PRIMARY KEY (ID);

prompt Creating table ACCOUNTING_JOURNAL...

CREATE TABLE ACCOUNTING_JOURNAL (
   ID           NUMBER(1)  NOT NULL
  ,CLIENT_ID    NUMBER(1)  NOT NULL
  ,NAME         VARCHAR2(1)  NOT NULL
  ,DESCRIPTION  VARCHAR2(1)  NOT NULL
  ,ACCSCHEMA_ID NUMBER(1)  NOT NULL
);
ALTER TABLE ACCOUNTING_JOURNAL ADD CONSTRAINT PK_ACCJOURN PRIMARY KEY (ID);
ALTER TABLE ACCOUNTING_JOURNAL ADD CONSTRAINT UK_ACCJOURN UNIQUE (CLIENT_ID,ACCSCHEMA_ID,NAME);

prompt Creating table ACCOUNTING_PERIOD...

CREATE TABLE ACCOUNTING_PERIOD (
   ID               NUMBER(1)  NOT NULL
  ,CLIENT_ID        NUMBER(1)  NOT NULL
  ,ACCYEAR          VARCHAR2(1)  NOT NULL
  ,NAME             VARCHAR2(1)  NOT NULL
  ,STARTDATE        DATE NOT NULL
  ,ENDDATE          DATE NOT NULL
  ,CLOSED           CHAR(1) NOT NULL
  ,CREATEDON        DATE NOT NULL
  ,CREATEDBY        VARCHAR2(1)  NOT NULL
  ,MODIFIEDON       DATE NOT NULL
  ,MODIFIEDBY       VARCHAR2(1)  NOT NULL
  ,PREV_PERIOD_NAME VARCHAR2(1) 
  ,NOTES            VARCHAR2(1) 
  ,PERIODTYPE       VARCHAR2(1) 
  ,PROCESSING       VARCHAR2(1) 
  ,OPENED           CHAR(1) NOT NULL
);
ALTER TABLE ACCOUNTING_PERIOD ADD CONSTRAINT PK_ACCPERIOD PRIMARY KEY (ID);
ALTER TABLE ACCOUNTING_PERIOD ADD CONSTRAINT UK_ACCPERIOD UNIQUE (CLIENT_ID,NAME);

prompt Creating table ACCOUNTING_YEAR...

CREATE TABLE ACCOUNTING_YEAR (
   ID             NUMBER(1)  NOT NULL
  ,CLIENT_ID      NUMBER(1)  NOT NULL
  ,NAME           VARCHAR2(1)  NOT NULL
  ,STARTDATE      DATE NOT NULL
  ,ENDDATE        DATE NOT NULL
  ,PREV_YEAR_NAME VARCHAR2(1) 
  ,NEXT_YEAR_NAME VARCHAR2(1) 
  ,CREATEDON      DATE NOT NULL
  ,CREATEDBY      VARCHAR2(1)  NOT NULL
  ,MODIFIEDON     DATE NOT NULL
  ,MODIFIEDBY     VARCHAR2(1)  NOT NULL
  ,NOTES          VARCHAR2(1) 
  ,CLOSED         CHAR(1)
  ,OPENED         CHAR(1)
);
ALTER TABLE ACCOUNTING_YEAR ADD CONSTRAINT PK_ACCYEAR PRIMARY KEY (ID);
ALTER TABLE ACCOUNTING_YEAR ADD CONSTRAINT UK_ACCYEAR UNIQUE (CLIENT_ID,NAME);

prompt Creating table ACCOUNT_BALANCE...

CREATE TABLE ACCOUNT_BALANCE (
   ID            NUMBER(1)  NOT NULL
  ,CLIENT_ID     NUMBER(1)  NOT NULL
  ,ACCSCHEMA_ID  NUMBER(1)  NOT NULL
  ,ACCPERIOD_ID  NUMBER(1)  NOT NULL
  ,ACCOUNT       VARCHAR2(1)  NOT NULL
  ,OPEN_BALANCE  NUMBER(1)  NOT NULL
  ,CLOSE_BALANCE NUMBER(1)  NOT NULL
  ,TOTAL_CR      NUMBER(1)  NOT NULL
  ,TOTAL_DB      NUMBER(1)  NOT NULL
);
ALTER TABLE ACCOUNT_BALANCE ADD CONSTRAINT PK_ACCTBAL PRIMARY KEY (ID);

prompt Creating table ACCOUNT_GROUP...

CREATE TABLE ACCOUNT_GROUP (
   ID           NUMBER(1)  NOT NULL
  ,ACCSCHEMA_ID NUMBER(1)  NOT NULL
  ,CODE         VARCHAR2(1)  NOT NULL
  ,NAME         VARCHAR2(1)  NOT NULL
);
ALTER TABLE ACCOUNT_GROUP ADD CONSTRAINT PK_ACCTGRP PRIMARY KEY (ID);
ALTER TABLE ACCOUNT_GROUP ADD CONSTRAINT UK_ACCTGRP UNIQUE (ACCSCHEMA_ID,CODE);

prompt Creating table ACCOUNT_MOVEMENT...

CREATE TABLE ACCOUNT_MOVEMENT (
   ID           NUMBER(1)  NOT NULL
  ,CLIENT_ID    NUMBER(1)  NOT NULL
  ,POSTING_DATE DATE NOT NULL
  ,ACCDOC_ID    NUMBER(1)  NOT NULL
  ,ACCDOCLIN_ID NUMBER(1)  NOT NULL
  ,CR_ACCT      VARCHAR2(1)  NOT NULL
  ,DB_ACCT      VARCHAR2(1)  NOT NULL
  ,CR_AMOUNT    NUMBER(1)  NOT NULL
  ,DB_AMOUNT    NUMBER(1)  NOT NULL
  ,CREATEDON    DATE NOT NULL
  ,CREATEDBY    VARCHAR2(1)  NOT NULL
);
ALTER TABLE ACCOUNT_MOVEMENT ADD CONSTRAINT PK_ACCTMVM PRIMARY KEY (ID);

prompt Creating table ACCRUAL...

CREATE TABLE ACCRUAL (
   ID          NUMBER(1)  NOT NULL
  ,CLIENT_ID   NUMBER(1)  NOT NULL
  ,BPARTNER_ID NUMBER(1)  NOT NULL
);
ALTER TABLE ACCRUAL ADD CONSTRAINT PK_ACCRUAL PRIMARY KEY (ID);

prompt Creating table ACC_SCHEMA...

CREATE TABLE ACC_SCHEMA (
   ID         NUMBER(1)  NOT NULL
  ,NAME       VARCHAR2(1)  NOT NULL
  ,CLIENT_ID  NUMBER(1)  NOT NULL
  ,CREATEDON  DATE NOT NULL
  ,CREATEDBY  VARCHAR2(1)  NOT NULL
  ,MODIFIEDON DATE NOT NULL
  ,MODIFIEDBY VARCHAR2(1)  NOT NULL
  ,IS_DEFAULT CHAR(1) NOT NULL
);
ALTER TABLE ACC_SCHEMA ADD CONSTRAINT PK_ACCSCHEMA PRIMARY KEY (ID);

prompt Creating table ACC_SCHEMA_ACCT...

CREATE TABLE ACC_SCHEMA_ACCT (
   ID             NUMBER(1)  NOT NULL
  ,ACCSCHEMA_ID   NUMBER(1)  NOT NULL
  ,ACCOUNT        VARCHAR2(1)  NOT NULL
  ,NAME           VARCHAR2(1)  NOT NULL
  ,PARENT_ACCOUNT VARCHAR2(1) 
  ,ACCJOURNAL_ID  NUMBER(1)  NOT NULL
  ,ACCGRP_ID      NUMBER(1)  NOT NULL
);
ALTER TABLE ACC_SCHEMA_ACCT ADD CONSTRAINT PK_ACCSCHACCT PRIMARY KEY (ID);
ALTER TABLE ACC_SCHEMA_ACCT ADD CONSTRAINT UK_ACCSCHACCT UNIQUE (ACCSCHEMA_ID,ACCOUNT);

prompt Creating table ACC_SCHEMA_ATTR...

CREATE TABLE ACC_SCHEMA_ATTR (
   ID             NUMBER(1)  NOT NULL
  ,ACCSCHEMA_ID   NUMBER(1) 
  ,PROPERTY_NAME  VARCHAR2(1) 
  ,PROPERTY_VALUE VARCHAR2(1) 
  ,CREATEDON      DATE
  ,CREATEDBY      VARCHAR2(1) 
  ,MODIFIEDON     DATE
  ,MODIFIEDBY     VARCHAR2(1) 
);
ALTER TABLE ACC_SCHEMA_ATTR ADD CONSTRAINT PK_ACCSCHEMAATTR PRIMARY KEY (ID);
ALTER TABLE ACC_SCHEMA_ATTR ADD CONSTRAINT UK_ACCSCHEMAATTR UNIQUE (ACCSCHEMA_ID,PROPERTY_NAME);

prompt Creating table ACC_SCHEMA_ATTR_DEF...

CREATE TABLE ACC_SCHEMA_ATTR_DEF (
   ID            NUMBER(1)  NOT NULL
  ,PROPERTY_NAME VARCHAR2(1)  NOT NULL
  ,PROPERTY_TYPE VARCHAR2(1) 
  ,DESCRIPTION   VARCHAR2(1) 
  ,CREATEDON     DATE
  ,CREATEDBY     VARCHAR2(1) 
  ,MODIFIEDON    DATE
  ,MODIFIEDBY    VARCHAR2(1) 
);
ALTER TABLE ACC_SCHEMA_ATTR_DEF ADD CONSTRAINT PK_ACCSCHATTRDEF PRIMARY KEY (ID);
ALTER TABLE ACC_SCHEMA_ATTR_DEF ADD CONSTRAINT UK_ACCSCHATTRDEF UNIQUE (PROPERTY_NAME);

prompt Creating table ACC_SCHEMA_ATTR_TYPE...

CREATE TABLE ACC_SCHEMA_ATTR_TYPE (
   ID          NUMBER(1)  NOT NULL
  ,CODE        VARCHAR2(1) 
  ,DESCRIPTION VARCHAR2(1) 
);
ALTER TABLE ACC_SCHEMA_ATTR_TYPE ADD CONSTRAINT PK_ACCSCHATTRTYPE PRIMARY KEY (ID);
ALTER TABLE ACC_SCHEMA_ATTR_TYPE ADD CONSTRAINT UK_ACCSCHATTRTYPE UNIQUE (CODE);

prompt Creating table ASSET...

CREATE TABLE ASSET (
   ID                     NUMBER(1)  NOT NULL
  ,CLIENT_ID              NUMBER(1)  NOT NULL
  ,CLIORG_ID              NUMBER(1) 
  ,PRODUCT_ID             NUMBER(1) 
  ,ASSETGRP_ID            NUMBER(1)  NOT NULL
  ,NAME                   VARCHAR2(1)  NOT NULL
  ,NOTES                  VARCHAR2(1) 
  ,QUANTITY               NUMBER(1)  NOT NULL
  ,SERIAL_NO              VARCHAR2(1) 
  ,IS_ACTIVE              CHAR(1) NOT NULL
  ,IS_DEPRECIATED         CHAR(1) NOT NULL
  ,IS_DISPOSED            CHAR(1) NOT NULL
  ,IS_OWNED               CHAR(1) NOT NULL
  ,IS_INPOSESSION         CHAR(1) NOT NULL
  ,LAST_MAINTENANCE_DATE  DATE
  ,NEXT_MAINTENENCE_DATE  DATE
  ,MAINTENANCE_PLAN_ID    NUMBER(1) 
  ,WITH_DEPRECIATION      CHAR(1) NOT NULL
  ,DEPREC_MONTHS          NUMBER(1) 
  ,DEPREC_BASE_VALUE      NUMBER(1) 
  ,DEPREC_MONTHS_REMAINED NUMBER(1) 
  ,BPARTNER_ID            NUMBER(1) 
  ,INUSE_BPARTNER_ID      NUMBER(1) 
  ,CREATEDON              DATE NOT NULL
  ,CREATEDBY              VARCHAR2(1)  NOT NULL
  ,MODIFIEDON             DATE NOT NULL
  ,MODIFIEDBY             VARCHAR2(1)  NOT NULL
);
ALTER TABLE ASSET ADD CONSTRAINT PK_ASSET PRIMARY KEY (ID);

prompt Creating table ASSET_GROUP...

CREATE TABLE ASSET_GROUP (
   ID         NUMBER(1)  NOT NULL
  ,CLIENT_ID  NUMBER(1)  NOT NULL
  ,CODE       VARCHAR2(1)  NOT NULL
  ,NAME       VARCHAR2(1)  NOT NULL
  ,CREATEDON  DATE NOT NULL
  ,CREATEDBY  VARCHAR2(1)  NOT NULL
  ,MODIFIEDON DATE NOT NULL
  ,MODIFIEDBY VARCHAR2(1)  NOT NULL
);

prompt Creating table BANK...

CREATE TABLE BANK (
   ID          NUMBER(1)  NOT NULL
  ,CODE        VARCHAR2(1)  NOT NULL
  ,NAME        VARCHAR2(1)  NOT NULL
  ,SWIFTCODE   VARCHAR2(1) 
  ,LOCATION_ID NUMBER(1) 
  ,CREATEDON   DATE NOT NULL
  ,CREATEDBY   VARCHAR2(1)  NOT NULL
  ,MODIFIEDON  DATE NOT NULL
  ,MODIFIEDBY  VARCHAR2(1)  NOT NULL
);
ALTER TABLE BANK ADD CONSTRAINT PK_BANK PRIMARY KEY (ID);
ALTER TABLE BANK ADD CONSTRAINT UK_BANK UNIQUE (CODE);

prompt Creating table BANK_AGENCY...

CREATE TABLE BANK_AGENCY (
   ID         NUMBER(1)  NOT NULL
  ,BANK_CODE  VARCHAR2(1)  NOT NULL
  ,NAME       VARCHAR2(1)  NOT NULL
  ,TYPE       VARCHAR2(1)  NOT NULL
  ,CODE       VARCHAR2(1)  NOT NULL
  ,ADRESS     VARCHAR2(1) 
  ,CREATEDON  DATE
  ,CREATEDBY  VARCHAR2(1) 
  ,MODIFIEDON DATE
  ,MODIFIEDBY VARCHAR2(1) 
);
ALTER TABLE BANK_AGENCY ADD CONSTRAINT PK_BANKAG PRIMARY KEY (ID);
ALTER TABLE BANK_AGENCY ADD CONSTRAINT UK_BANKAG UNIQUE (BANK_CODE,CODE);

prompt Creating table BILLING_CYCLE...

CREATE TABLE BILLING_CYCLE (
   ID                NUMBER(1)  NOT NULL
  ,BILLCYCCLASS_CODE VARCHAR2(1)  NOT NULL
  ,CLIENT_ID         NUMBER(1)  NOT NULL
  ,STARTDATE         DATE NOT NULL
  ,ENDDATE           DATE NOT NULL
  ,NAME              VARCHAR2(1) 
  ,CLOSED            CHAR(1) NOT NULL
  ,CREATEDON         DATE NOT NULL
  ,CREATEDBY         VARCHAR2(1)  NOT NULL
  ,MODIFIEDON        DATE NOT NULL
  ,MODIFIEDBY        VARCHAR2(1)  NOT NULL
);
ALTER TABLE BILLING_CYCLE ADD CONSTRAINT PK_BILLCYC PRIMARY KEY (ID);

prompt Creating table BILLING_CYCLE_CLASS...

CREATE TABLE BILLING_CYCLE_CLASS (
   CODE       VARCHAR2(1)  NOT NULL
  ,NAME       VARCHAR2(1) 
  ,STARTDAY   NUMBER(1) 
  ,CREATEDON  DATE NOT NULL
  ,CREATEDBY  VARCHAR2(1)  NOT NULL
  ,MODIFIEDON DATE NOT NULL
  ,MODIFIEDBY VARCHAR2(1)  NOT NULL
);
ALTER TABLE BILLING_CYCLE_CLASS ADD CONSTRAINT PK_BILLCYCCLASS PRIMARY KEY (CODE);

prompt Creating table BPARTNER...

CREATE TABLE BPARTNER (
   ID                      NUMBER(1)  NOT NULL
  ,NAME                    VARCHAR2(1)  NOT NULL
  ,BPARTNER_TYPE           VARCHAR2(1) 
  ,BPARTNER_ID             NUMBER(1) 
  ,CODE                    VARCHAR2(1)  NOT NULL
  ,COPIED_FROM_BPARTNER_ID NUMBER(1) 
  ,TAX_NUMBER              VARCHAR2(1) 
  ,TAX_NUMBER_TYPE         VARCHAR2(1) 
  ,CREATEDON               DATE NOT NULL
  ,CREATEDBY               VARCHAR2(1)  NOT NULL
  ,MODIFIEDON              DATE NOT NULL
  ,MODIFIEDBY              VARCHAR2(1)  NOT NULL
  ,COMPANY_REG_NR          VARCHAR2(1) 
  ,PHONE                   VARCHAR2(1) 
  ,EMAIL                   VARCHAR2(1) 
  ,FAX                     VARCHAR2(1) 
  ,CLIENT_ID               NUMBER(1)  NOT NULL
  ,CUSTGROUP_CODE          VARCHAR2(1) 
  ,CREDITCLASS_CODE        VARCHAR2(1) 
  ,PAYMETHOD_CODE          VARCHAR2(1) 
  ,PAYTERMCLASS_CODE       VARCHAR2(1) 
  ,MAX_CREDIT_LIMIT        NUMBER(1) 
  ,MAX_PAYMENT_TERM        NUMBER(1) 
  ,IS_CUSTOMER             CHAR(1) NOT NULL
  ,IS_VENDOR               CHAR(1) NOT NULL
  ,IS_EMPLOYEE             CHAR(1) NOT NULL
  ,IS_ONETIME              CHAR(1) NOT NULL
);
ALTER TABLE BPARTNER ADD CONSTRAINT PK_BPARTNER PRIMARY KEY (ID);

prompt Creating table BPCONTACT_PHONE...

CREATE TABLE BPCONTACT_PHONE (
   ID           NUMBER(1)  NOT NULL
  ,BPCONTACT_ID NUMBER(1)  NOT NULL
  ,CMNCT_TYPE   VARCHAR2(1)  NOT NULL
  ,CMNCT_VALUE  VARCHAR2(1)  NOT NULL
  ,NOTES        VARCHAR2(1) 
  ,CREATEDON    DATE NOT NULL
  ,CREATEDBY    VARCHAR2(1)  NOT NULL
  ,MODIFIEDON   DATE NOT NULL
  ,MODIFIEDBY   VARCHAR2(1)  NOT NULL
);
ALTER TABLE BPCONTACT_PHONE ADD CONSTRAINT PK_BPCONTACTPH PRIMARY KEY (ID);

prompt Creating table BP_ACCOUNT_CUSTOMER...

CREATE TABLE BP_ACCOUNT_CUSTOMER (
   ID                  NUMBER(1)  NOT NULL
  ,BPARTNER_ID         NUMBER(1)  NOT NULL
  ,CLIENT_ID           NUMBER(1)  NOT NULL
  ,ACCT_RECEIVABLE     VARCHAR2(1) 
  ,ACCT_PREPAYMENT     VARCHAR2(1) 
  ,ACCT_RECEVABLE_SRVC VARCHAR2(1) 
  ,CREATEDON           DATE NOT NULL
  ,CREATEDBY           VARCHAR2(1)  NOT NULL
  ,MODIFIEDON          DATE NOT NULL
  ,MODIFIEDBY          VARCHAR2(1)  NOT NULL
  ,ACCSCHEMA_ID        NUMBER(1)  NOT NULL
);
ALTER TABLE BP_ACCOUNT_CUSTOMER ADD CONSTRAINT PK_BPACCCUST PRIMARY KEY (ID);
ALTER TABLE BP_ACCOUNT_CUSTOMER ADD CONSTRAINT UK_BPACCCUST UNIQUE (CLIENT_ID,BPARTNER_ID,ACCSCHEMA_ID);

prompt Creating table BP_ACCOUNT_INTERNAL...

CREATE TABLE BP_ACCOUNT_INTERNAL (
   ID              NUMBER(1)  NOT NULL
  ,CLIENT_ID       NUMBER(1)  NOT NULL
  ,BPARTNER_ID     NUMBER(1)  NOT NULL
  ,ACCSCHEMA_ID    NUMBER(1)  NOT NULL
  ,CREATEDON       DATE NOT NULL
  ,CREATEDBY       VARCHAR2(1)  NOT NULL
  ,MODIFIEDON      DATE NOT NULL
  ,MODIFIEDBY      VARCHAR2(1)  NOT NULL
  ,ACCT_EXPENSE    VARCHAR2(1)  NOT NULL
  ,ACCT_PREPAYMENT VARCHAR2(1)  NOT NULL
);
ALTER TABLE BP_ACCOUNT_INTERNAL ADD CONSTRAINT PK_BPACCINT PRIMARY KEY (ID);
ALTER TABLE BP_ACCOUNT_INTERNAL ADD CONSTRAINT UK_BPACCINT UNIQUE (CLIENT_ID,BPARTNER_ID,ACCSCHEMA_ID);

prompt Creating table BP_ACCOUNT_VENDOR...

CREATE TABLE BP_ACCOUNT_VENDOR (
   ID                  NUMBER(1)  NOT NULL
  ,CLIENT_ID           NUMBER(1)  NOT NULL
  ,BPARTNER_ID         NUMBER(1)  NOT NULL
  ,ACCT_PREPAYMENT     VARCHAR2(1) 
  ,ACCT_LIABILITY      VARCHAR2(1) 
  ,ACCT_LIABILITY_SRVC VARCHAR2(1) 
  ,CREATEDON           DATE NOT NULL
  ,CREATEDBY           VARCHAR2(1)  NOT NULL
  ,MODIFIEDON          DATE NOT NULL
  ,MODIFIEDBY          VARCHAR2(1)  NOT NULL
  ,ACCSCHEMA_ID        NUMBER(1)  NOT NULL
);
ALTER TABLE BP_ACCOUNT_VENDOR ADD CONSTRAINT PK_BPACCVEND PRIMARY KEY (ID);
ALTER TABLE BP_ACCOUNT_VENDOR ADD CONSTRAINT UK_BPACCVEND UNIQUE (CLIENT_ID,BPARTNER_ID,ACCSCHEMA_ID);

prompt Creating table BP_ADRESS...

CREATE TABLE BP_ADRESS (
   ID           NUMBER(1)  NOT NULL
  ,BPARTNER_ID  NUMBER(1)  NOT NULL
  ,COUNTRY_CODE VARCHAR2(1) 
  ,REGION_CODE  VARCHAR2(1) 
  ,CITY         VARCHAR2(1) 
  ,CITY_ID      NUMBER(1) 
  ,STREET       VARCHAR2(1) 
  ,STREET_ID    NUMBER(1) 
  ,NO           VARCHAR2(1) 
  ,BUILDING     VARCHAR2(1) 
  ,FLOOR        VARCHAR2(1) 
  ,APT          VARCHAR2(1) 
  ,ADRESS_TYPE  VARCHAR2(1) 
  ,NOTES        VARCHAR2(1) 
  ,ENTRANCE     VARCHAR2(1) 
  ,IS_BILLING   CHAR(1)
  ,IS_DELIVERY  CHAR(1)
  ,NAME         VARCHAR2(1)  NOT NULL
  ,CREATEDON    DATE
  ,CREATEDBY    VARCHAR2(1) 
  ,MODIFIEDON   DATE
  ,MODIFIEDBY   VARCHAR2(1) 
  ,ZIP          VARCHAR2(1) 
  ,ADRESS       VARCHAR2(1) 
  ,IS_DETAILED  CHAR(1)
);
ALTER TABLE BP_ADRESS ADD CONSTRAINT PK_BPADR PRIMARY KEY (ID);

prompt Creating table BP_BALANCE...

CREATE TABLE BP_BALANCE (
   ID          NUMBER(1)  NOT NULL
  ,CLIENT_ID   NUMBER(1) 
  ,BPARTNER_ID NUMBER(1) 
  ,IINV_ID     NUMBER(1) 
  ,RINV_ID     NUMBER(1) 
  ,PAYMENT_ID  NUMBER(1) 
);
ALTER TABLE BP_BALANCE ADD CONSTRAINT PK_BPBALANCE PRIMARY KEY (ID);

prompt Creating table BP_BANKACCOUNT...

CREATE TABLE BP_BANKACCOUNT (
   ID          NUMBER(1)  NOT NULL
  ,BANK_CODE   VARCHAR2(1)  NOT NULL
  ,IBAN        VARCHAR2(1)  NOT NULL
  ,CURRENCY    VARCHAR2(1)  NOT NULL
  ,CREATEDON   DATE NOT NULL
  ,CREATEDBY   VARCHAR2(1)  NOT NULL
  ,MODIFIEDON  DATE NOT NULL
  ,MODIFIEDBY  VARCHAR2(1)  NOT NULL
  ,BPARTNER_ID NUMBER(1)  NOT NULL
  ,BANKAG_CODE VARCHAR2(1) 
);
ALTER TABLE BP_BANKACCOUNT ADD CONSTRAINT PK_BPBANKACCT PRIMARY KEY (ID);

prompt Creating table BP_CONTACT...

CREATE TABLE BP_CONTACT (
   ID          NUMBER(1)  NOT NULL
  ,BPARTNER_ID NUMBER(1)  NOT NULL
  ,NAME        VARCHAR2(1)  NOT NULL
  ,FIRSTNAME   VARCHAR2(1) 
  ,LASTNAME    VARCHAR2(1) 
  ,PHONE       VARCHAR2(1) 
  ,EMAIL       VARCHAR2(1) 
  ,FAX         VARCHAR2(1) 
  ,NOTES       VARCHAR2(1) 
  ,MOBILE      VARCHAR2(1) 
  ,CREATEDON   DATE NOT NULL
  ,CREATEDBY   VARCHAR2(1)  NOT NULL
  ,MODIFIEDON  DATE NOT NULL
  ,MODIFIEDBY  VARCHAR2(1)  NOT NULL
  ,BIRTHDATE   DATE
);
ALTER TABLE BP_CONTACT ADD CONSTRAINT PK_BPCONTACT PRIMARY KEY (ID);

prompt Creating table BP_CONTRACT...

CREATE TABLE BP_CONTRACT (
   ID               NUMBER(1)  NOT NULL
  ,DOC_NO           VARCHAR2(1)  NOT NULL
  ,DOC_DATE         DATE NOT NULL
  ,CLIENT_ID        NUMBER(1)  NOT NULL
  ,CUST_BPARTNER_ID NUMBER(1)  NOT NULL
  ,CONTRTYPE_CODE   VARCHAR2(1)  NOT NULL
  ,STARTDATE        DATE NOT NULL
  ,ENDDATE          DATE
  ,NOTES            VARCHAR2(1) 
  ,BPCONTR_ID       NUMBER(1) 
  ,CREATEDON        DATE NOT NULL
  ,CREATEDBY        VARCHAR2(1)  NOT NULL
  ,MODIFIEDON       DATE NOT NULL
  ,MODIFIEDBY       VARCHAR2(1)  NOT NULL
  ,CONTRSTAT_CODE   VARCHAR2(1) 
  ,SUPP_BPARTNER_ID NUMBER(1)  NOT NULL
);
ALTER TABLE BP_CONTRACT ADD CONSTRAINT PK_BPCONTR PRIMARY KEY (ID);

prompt Creating table BP_PHONE...

CREATE TABLE BP_PHONE (
   ID          NUMBER(1)  NOT NULL
  ,BPARTNER_ID NUMBER(1)  NOT NULL
  ,CMNCT_TYPE  VARCHAR2(1)  NOT NULL
  ,CMNCT_VALUE VARCHAR2(1)  NOT NULL
  ,CREATEDON   DATE NOT NULL
  ,CREATEDBY   VARCHAR2(1)  NOT NULL
  ,MODIFIEDON  DATE NOT NULL
  ,MODIFIEDBY  VARCHAR2(1)  NOT NULL
  ,NOTES       VARCHAR2(1) 
);
ALTER TABLE BP_PHONE ADD CONSTRAINT PK_BPPHONE PRIMARY KEY (ID);

prompt Creating table BP_SUBSCRIPTION...

CREATE TABLE BP_SUBSCRIPTION (
   ID           NUMBER(1)  NOT NULL
  ,CLIENT_ID    NUMBER(1)  NOT NULL
  ,BPARTNER_ID  NUMBER(1)  NOT NULL
  ,BPCONTR_ID   NUMBER(1) 
  ,SUBSC_CODE   VARCHAR2(1)  NOT NULL
  ,STARTDATE    DATE NOT NULL
  ,ENDDATE      DATE
  ,BPACCCUST_ID NUMBER(1)  NOT NULL
  ,CREATEDON    DATE NOT NULL
  ,CREATEDBY    VARCHAR2(1)  NOT NULL
  ,MODIFIEDON   DATE NOT NULL
  ,MODIFIEDBY   VARCHAR2(1)  NOT NULL
);
ALTER TABLE BP_SUBSCRIPTION ADD CONSTRAINT PK_BPSUBSC PRIMARY KEY (ID);

prompt Creating table BUDGET...

CREATE TABLE BUDGET (
   ID        NUMBER(1)  NOT NULL
  ,CLIENT_ID NUMBER(1) 
);
ALTER TABLE BUDGET ADD CONSTRAINT PK_BUDGET PRIMARY KEY (ID);

prompt Creating table CITY...

CREATE TABLE CITY (
   ID           NUMBER(1)  NOT NULL
  ,COUNTRY_CODE VARCHAR2(1)  NOT NULL
  ,REGION_CODE  VARCHAR2(1)  NOT NULL
  ,NAME         VARCHAR2(1)  NOT NULL
  ,AREA_CODE    VARCHAR2(1) 
  ,POSTAL_CODE  VARCHAR2(1) 
  ,ACTIVE       CHAR(1) NOT NULL
  ,CREATEDON    DATE NOT NULL
  ,CREATEDBY    VARCHAR2(1)  NOT NULL
  ,MODIFIEDON   DATE NOT NULL
  ,MODIFIEDBY   VARCHAR2(1)  NOT NULL
  ,CODE         VARCHAR2(1)  NOT NULL
);
ALTER TABLE CITY ADD CONSTRAINT PK_CITY PRIMARY KEY (ID);
ALTER TABLE CITY ADD CONSTRAINT UK_CITY UNIQUE (COUNTRY_CODE,REGION_CODE,CODE);

prompt Creating table CLIENT...

CREATE TABLE CLIENT (
   ID             NUMBER(1)  NOT NULL
  ,NAME           VARCHAR2(1) 
  ,BPARTNER_ID    NUMBER(1) 
  ,CODE           VARCHAR2(1) 
  ,DEFAULT_CLIENT CHAR(1)
);
ALTER TABLE CLIENT ADD CONSTRAINT PK_CLIENT PRIMARY KEY (ID);
ALTER TABLE CLIENT ADD CONSTRAINT UK_CLIENT UNIQUE (CODE);

prompt Creating table COMMUNIC_TYPE...

CREATE TABLE COMMUNIC_TYPE (
   CODE VARCHAR2(1) 
);
ALTER TABLE COMMUNIC_TYPE ADD CONSTRAINT UK_CMNCTYP UNIQUE (CODE);

prompt Creating table CONTRACT_STATUS...

CREATE TABLE CONTRACT_STATUS (
   CODE   VARCHAR2(1)  NOT NULL
  ,NAME   VARCHAR2(1) 
  ,ACTIVE CHAR(1)
);
ALTER TABLE CONTRACT_STATUS ADD CONSTRAINT PK_CONTRSTAT PRIMARY KEY (CODE);

prompt Creating table CONTRACT_TYPE...

CREATE TABLE CONTRACT_TYPE (
   CODE        VARCHAR2(1)  NOT NULL
  ,NAME        VARCHAR2(1)  NOT NULL
  ,DESCRIPTION VARCHAR2(1) 
  ,ACTIVE      CHAR(1) NOT NULL
);
ALTER TABLE CONTRACT_TYPE ADD CONSTRAINT PK_CONTRTYPE PRIMARY KEY (CODE);

prompt Creating table COST_CENTER...

CREATE TABLE COST_CENTER (
   ID        NUMBER(1)  NOT NULL
  ,CLIENT_ID NUMBER(1)  NOT NULL
  ,CODE      VARCHAR2(1)  NOT NULL
  ,NAME      VARCHAR2(1)  NOT NULL
  ,ACTIVE    CHAR(1) NOT NULL
);
ALTER TABLE COST_CENTER ADD CONSTRAINT PK_COSTCENTER PRIMARY KEY (ID);
ALTER TABLE COST_CENTER ADD CONSTRAINT UK_COSTCENTER UNIQUE (CODE);

prompt Creating table COUNTRY...

CREATE TABLE COUNTRY (
   ID           NUMBER(1)  NOT NULL
  ,CODE         VARCHAR2(1)  NOT NULL
  ,NAME         VARCHAR2(1)  NOT NULL
  ,ACTIVE       CHAR(1) NOT NULL
  ,WITH_REGIONS CHAR(1) NOT NULL
  ,WITH_CITIES  CHAR(1) NOT NULL
  ,ISO2         VARCHAR2(1) 
);
ALTER TABLE COUNTRY ADD CONSTRAINT PK_COUNTRY PRIMARY KEY (ID);
ALTER TABLE COUNTRY ADD CONSTRAINT UK_COUNTRY UNIQUE (CODE);

prompt Creating table CREDIT_CLASS...

CREATE TABLE CREDIT_CLASS (
   CODE                  VARCHAR2(1)  NOT NULL
  ,NAME                  VARCHAR2(1)  NOT NULL
  ,CLIENT_ID             NUMBER(1) 
  ,CREDIT_LIMIT          NUMBER(1) 
  ,CREDIT_LIMIT_CURRENCY VARCHAR2(1) 
  ,NOTES                 VARCHAR2(1) 
  ,CREATEDON             DATE NOT NULL
  ,CREATEDBY             VARCHAR2(1)  NOT NULL
  ,MODIFIEDON            DATE NOT NULL
  ,MODIFIEDBY            VARCHAR2(1)  NOT NULL
  ,ACTIVE                CHAR(1) NOT NULL
);

prompt Creating table CURRENCY...

CREATE TABLE CURRENCY (
   ID           NUMBER(1)  NOT NULL
  ,CODE         VARCHAR2(1)  NOT NULL
  ,NAME         VARCHAR2(1)  NOT NULL
  ,ACTIVE       CHAR(1) NOT NULL
  ,ACCOUNT_GAIN VARCHAR2(1) 
  ,ACCOUNT_LOSS VARCHAR2(1) 
);
ALTER TABLE CURRENCY ADD CONSTRAINT PK_CURRENCY PRIMARY KEY (ID);
ALTER TABLE CURRENCY ADD CONSTRAINT UK_CURRENCY UNIQUE (CODE);

prompt Creating table CURRENCY_AVG_RATE...

CREATE TABLE CURRENCY_AVG_RATE (
   ID            NUMBER(1)  NOT NULL
  ,CRNCYEXCH_ID  NUMBER(1)  NOT NULL
  ,EXCHANGE_RATE NUMBER(1)  NOT NULL
  ,PERIOD_ID     NUMBER(1)  NOT NULL
);
ALTER TABLE CURRENCY_AVG_RATE ADD CONSTRAINT PK_CRNCYAVGRATE PRIMARY KEY (ID);

prompt Creating table CURRENCY_XRATE...

CREATE TABLE CURRENCY_XRATE (
   ID            NUMBER(1)  NOT NULL
  ,CURRENCY_FROM VARCHAR2(1)  NOT NULL
  ,XRATE         NUMBER(1)  NOT NULL
  ,CREATEDON     DATE NOT NULL
  ,CREATEDBY     VARCHAR2(1)  NOT NULL
  ,MODIFIEDON    DATE NOT NULL
  ,MODIFIEDBY    VARCHAR2(1)  NOT NULL
  ,VALID_FROM    DATE NOT NULL
  ,VALID_TO      DATE
  ,CURRENCY_TO   VARCHAR2(1) 
);
ALTER TABLE CURRENCY_XRATE ADD CONSTRAINT PK_CRNCYEXCHRATE PRIMARY KEY (ID);

prompt Creating table DELIVERY_AGENT...

CREATE TABLE DELIVERY_AGENT (
   ID     NUMBER(1)  NOT NULL
  ,CODE   VARCHAR2(1) 
  ,NAME   VARCHAR2(1) 
  ,ACTIVE CHAR(1)
);
ALTER TABLE DELIVERY_AGENT ADD CONSTRAINT PK_DLVRAGENT PRIMARY KEY (ID);
ALTER TABLE DELIVERY_AGENT ADD CONSTRAINT UK_DLVRAGENT UNIQUE (CODE);

prompt Creating table DOCUMENT_SERIAL...

CREATE TABLE DOCUMENT_SERIAL (
   ID            NUMBER(1)  NOT NULL
  ,CLIENT_ID     NUMBER(1)  NOT NULL
  ,DOCUMENT_TYPE VARCHAR2(1)  NOT NULL
  ,SERIAL        VARCHAR2(1)  NOT NULL
);
ALTER TABLE DOCUMENT_SERIAL ADD CONSTRAINT PK_DOCSER PRIMARY KEY (ID);
ALTER TABLE DOCUMENT_SERIAL ADD CONSTRAINT UK_DOCSER UNIQUE (CLIENT_ID,DOCUMENT_TYPE,SERIAL);

prompt Creating table DOCUMENT_SERIAL_NO...

CREATE TABLE DOCUMENT_SERIAL_NO (
   ID           NUMBER(1)  NOT NULL
  ,CLIENT_ID    NUMBER(1)  NOT NULL
  ,DOCSER_ID    NUMBER(1)  NOT NULL
  ,DOCSERRNG_ID NUMBER(1)  NOT NULL
  ,VALUE        NUMBER(1)  NOT NULL
  ,IS_ALLOCATED CHAR(1) NOT NULL
);
ALTER TABLE DOCUMENT_SERIAL_NO ADD CONSTRAINT PK_DOCSERNO PRIMARY KEY (ID);

prompt Creating table DOCUMENT_SERIAL_RANGE...

CREATE TABLE DOCUMENT_SERIAL_RANGE (
   ID           NUMBER(1)  NOT NULL
  ,DOCSER_ID    NUMBER(1)  NOT NULL
  ,MINVAL       NUMBER(1)  NOT NULL
  ,MAXVAL       NUMBER(1)  NOT NULL
  ,IS_INSTALLED CHAR(1) NOT NULL
  ,IS_CLOSED    CHAR(1) NOT NULL
);
ALTER TABLE DOCUMENT_SERIAL_RANGE ADD CONSTRAINT PK_DOCSERRNG PRIMARY KEY (ID);

prompt Creating table EMPLOYEE...

CREATE TABLE EMPLOYEE (
   ID         NUMBER(1)  NOT NULL
  ,FIRSTNAME  VARCHAR2(1)  NOT NULL
  ,LASTNAME   VARCHAR2(1)  NOT NULL
  ,CREATEDON  DATE NOT NULL
  ,CREATEDBY  VARCHAR2(1)  NOT NULL
  ,MODIFIEDON DATE NOT NULL
  ,MODIFIEDBY VARCHAR2(1)  NOT NULL
);
ALTER TABLE EMPLOYEE ADD CONSTRAINT PK_EMPL PRIMARY KEY (ID);

prompt Creating table EXPENSESHEET...

CREATE TABLE EXPENSESHEET (
   ID        NUMBER(1)  NOT NULL
  ,CLIENT_ID NUMBER(1)  NOT NULL
);
ALTER TABLE EXPENSESHEET ADD CONSTRAINT PK_EXPSHEET PRIMARY KEY (ID);

prompt Creating table IINVOICE...

CREATE TABLE IINVOICE (
   ID               NUMBER(1)  NOT NULL
  ,DOC_DATE         DATE NOT NULL
  ,DOC_NO           VARCHAR2(1)  NOT NULL
  ,CLIENT_ID        NUMBER(1)  NOT NULL
  ,ISSUER_ID        NUMBER(1)  NOT NULL
  ,RECEIVER_ID      NUMBER(1)  NOT NULL
  ,PAYBY_ID         NUMBER(1) 
  ,DOC_TYPE         VARCHAR2(1)  NOT NULL
  ,INV_STATUS       VARCHAR2(1) 
  ,DOC_CURRENCY     VARCHAR2(1)  NOT NULL
  ,TRANSTYPE_CODE   VARCHAR2(1) 
  ,DUE_DATE         DATE
  ,INV_LINE_COUNT   NUMBER(1) 
  ,REF_IINV_ID      NUMBER(1) 
  ,REF_IINV_DOC_NO  VARCHAR2(1) 
  ,ORDER_ID         NUMBER(1) 
  ,TOTAL_NET_AMOUNT NUMBER(1)  NOT NULL
  ,TOTAL_TAX_AMOUNT NUMBER(1)  NOT NULL
  ,TOTAL_AMOUNT     NUMBER(1)  NOT NULL
  ,CREATEDON        DATE NOT NULL
  ,CREATEDBY        VARCHAR2(1)  NOT NULL
  ,MODIFIEDON       DATE NOT NULL
  ,MODIFIEDBY       VARCHAR2(1)  NOT NULL
  ,IS_PRINTED       CHAR(1) NOT NULL
  ,NOTES            VARCHAR2(1) 
  ,CURRENCY_XRATE   NUMBER(1) 
  ,DOC_NO_SERIAL    VARCHAR2(1) 
  ,IS_POSTED        CHAR(1) NOT NULL
  ,VAT_RATE         NUMBER(1) 
  ,IS_INSERTED      CHAR(1)
  ,ACCT             VARCHAR2(1) 
  ,POSTEDON         DATE
  ,POSTEDBY         VARCHAR2(1) 
  ,ACCDOC_ID        NUMBER(1) 
  ,INSERTEDON       DATE
  ,INSERTEDBY       VARCHAR2(1) 
);
ALTER TABLE IINVOICE ADD CONSTRAINT PK_IINV PRIMARY KEY (ID);

prompt Creating table IINVOICE_ITEM...

CREATE TABLE IINVOICE_ITEM (
   ID             NUMBER(1)  NOT NULL
  ,IINV_ID        NUMBER(1)  NOT NULL
  ,LINE_NO        VARCHAR2(1)  NOT NULL
  ,PROD_ID        NUMBER(1)  NOT NULL
  ,QUANTITY       NUMBER(1)  NOT NULL
  ,QUANTITY_UNIT  VARCHAR2(1)  NOT NULL
  ,ORIG_PRICE     NUMBER(1)  NOT NULL
  ,NET_AMOUNT     NUMBER(1)  NOT NULL
  ,ORIG_CURRENCY  VARCHAR2(1) 
  ,PRICE          NUMBER(1) 
  ,CURRENCY_XRATE NUMBER(1) 
  ,CREATEDON      DATE NOT NULL
  ,CREATEDBY      VARCHAR2(1)  NOT NULL
  ,MODIFIEDON     DATE NOT NULL
  ,MODIFIEDBY     VARCHAR2(1)  NOT NULL
  ,IINVITEM_ID    NUMBER(1) 
  ,NOTES          VARCHAR2(1) 
  ,TAX_RATE       NUMBER(1) 
  ,TAX_AMOUNT     NUMBER(1) 
  ,CURRENCY       VARCHAR2(1)  NOT NULL
  ,SALES_ACCT     VARCHAR2(1) 
  ,TAX_ID         NUMBER(1) 
);
ALTER TABLE IINVOICE_ITEM ADD CONSTRAINT PK_IINVITEM PRIMARY KEY (ID);

prompt Creating table IINV_DOCTYP_ATTR...

CREATE TABLE IINV_DOCTYP_ATTR (
   ID            NUMBER(1)  NOT NULL
  ,IINVDOCTYP_ID NUMBER(1)  NOT NULL
  ,ACCSCHEMA_ID  NUMBER(1)  NOT NULL
  ,ATTR_NAME     VARCHAR2(1)  NOT NULL
  ,ATTR_VALUE    VARCHAR2(1) 
);
ALTER TABLE IINV_DOCTYP_ATTR ADD CONSTRAINT PK_IINVDOCTYPATT PRIMARY KEY (ID);

prompt Creating table IINV_DOC_TYPE...

CREATE TABLE IINV_DOC_TYPE (
   ID                NUMBER(1)  NOT NULL
  ,CODE              VARCHAR2(1)  NOT NULL
  ,NAME              VARCHAR2(1)  NOT NULL
  ,ACTIVE            CHAR(1) NOT NULL
  ,PRINT_REPORT_CODE VARCHAR2(1) 
  ,CLIENT_ID         NUMBER(1)  NOT NULL
  ,CREATEDON         DATE NOT NULL
  ,CREATEDBY         VARCHAR2(1)  NOT NULL
  ,MODIFIEDON        DATE NOT NULL
  ,MODIFIEDBY        VARCHAR2(1)  NOT NULL
);
ALTER TABLE IINV_DOC_TYPE ADD CONSTRAINT PK_IINVDOCTYPE PRIMARY KEY (ID);
ALTER TABLE IINV_DOC_TYPE ADD CONSTRAINT UK_IINVDOCTYPE UNIQUE (CODE);

prompt Creating table IMPEX_MAP...

CREATE TABLE IMPEX_MAP (
   ID          NUMBER(1)  NOT NULL
  ,CODE        VARCHAR2(1)  NOT NULL
  ,DESCRIPTION VARCHAR2(1)  NOT NULL
  ,CREATEDON   DATE NOT NULL
  ,CREATEDBY   VARCHAR2(1)  NOT NULL
  ,MODIFIEDON  DATE NOT NULL
  ,MODIFIEDBY  VARCHAR2(1)  NOT NULL
);
ALTER TABLE IMPEX_MAP ADD CONSTRAINT PK_IMPEXMAPITEM PRIMARY KEY (ID);
ALTER TABLE IMPEX_MAP ADD CONSTRAINT UK_IMPEXMAP UNIQUE (CODE);

prompt Creating table IMPEX_MAP_ITEM...

CREATE TABLE IMPEX_MAP_ITEM (
   ID            NUMBER(1)  NOT NULL
  ,IMPEXMAP_CODE VARCHAR2(1)  NOT NULL
  ,ITEM_NAME     VARCHAR2(1)  NOT NULL
  ,ITEM_TYPE     VARCHAR2(1)  NOT NULL
  ,CREATEDON     DATE NOT NULL
  ,CREATEDBY     VARCHAR2(1)  NOT NULL
  ,MODIFIEDON    DATE NOT NULL
  ,MODIFIEDBY    VARCHAR2(1)  NOT NULL
);
ALTER TABLE IMPEX_MAP_ITEM ADD CONSTRAINT UK_IMPEXMAPITEM UNIQUE (IMPEXMAP_CODE,ITEM_NAME);

prompt Creating table LANGUAGES...

CREATE TABLE LANGUAGES (
   ID     NUMBER(1)  NOT NULL
  ,CODE   VARCHAR2(1)  NOT NULL
  ,NAME   VARCHAR2(1)  NOT NULL
  ,ACTIVE CHAR(1) NOT NULL
);
ALTER TABLE LANGUAGES ADD CONSTRAINT PK_LANG PRIMARY KEY (ID);
ALTER TABLE LANGUAGES ADD CONSTRAINT UK_LANG UNIQUE (CODE);

prompt Creating table MENUBAR...

CREATE TABLE MENUBAR (
   CODE       VARCHAR2(1)  NOT NULL
  ,NAME       VARCHAR2(1)  NOT NULL
  ,IS_DEFAULT CHAR(1)
  ,POSITION   NUMBER(1) 
);
ALTER TABLE MENUBAR ADD CONSTRAINT PK_MENUBAR PRIMARY KEY (CODE);

prompt Creating table MENUITEM...

CREATE TABLE MENUITEM (
   ID           NUMBER(1)  NOT NULL
  ,MENUBAR_CODE VARCHAR2(1)  NOT NULL
  ,NAME         VARCHAR2(1)  NOT NULL
  ,POSITION     NUMBER(1)  NOT NULL
  ,MENUITEM_ID  NUMBER(1) 
  ,CODE         VARCHAR2(1) 
  ,LINK         VARCHAR2(1) 
  ,TARGET       VARCHAR2(1) 
  ,CREATEDON    DATE NOT NULL
  ,CREATEDBY    VARCHAR2(1)  NOT NULL
  ,MODIFIEDON   DATE NOT NULL
  ,MODIFIEDBY   VARCHAR2(1)  NOT NULL
  ,ACTIVE       CHAR(1) NOT NULL
);
ALTER TABLE MENUITEM ADD CONSTRAINT PK_MENUITEM PRIMARY KEY (ID);

prompt Creating table MENUITEM_PARAM...

CREATE TABLE MENUITEM_PARAM (
   ID          NUMBER(1)  NOT NULL
  ,MENUITEM_ID NUMBER(1)  NOT NULL
  ,PARAM_NAME  VARCHAR2(1)  NOT NULL
  ,PARAM_VALUE VARCHAR2(1) 
);
ALTER TABLE MENUITEM_PARAM ADD CONSTRAINT PK_MENUITEMPARAM PRIMARY KEY (ID);

prompt Creating table MENUITEM_ROLE...

CREATE TABLE MENUITEM_ROLE (
   ID          NUMBER(1)  NOT NULL
  ,MENUITEM_ID NUMBER(1)  NOT NULL
  ,ROLE_NAME   VARCHAR2(1)  NOT NULL
  ,CREATEDON   DATE NOT NULL
  ,CREATEDBY   VARCHAR2(1)  NOT NULL
  ,MODIFIEDON  DATE NOT NULL
  ,MODIFIEDBY  VARCHAR2(1)  NOT NULL
);
ALTER TABLE MENUITEM_ROLE ADD CONSTRAINT PK_MENUITEMROLE PRIMARY KEY (ID);
ALTER TABLE MENUITEM_ROLE ADD CONSTRAINT UK_MENUITEMROLE UNIQUE (MENUITEM_ID,ROLE_NAME);

prompt Creating table MENUITEM_TRL...

CREATE TABLE MENUITEM_TRL (
   ID          NUMBER(1)  NOT NULL
  ,MENUITEM_ID NUMBER(1)  NOT NULL
  ,LANG        VARCHAR2(1)  NOT NULL
  ,TRANSLATION VARCHAR2(1)  NOT NULL
  ,CREATEDON   DATE NOT NULL
  ,CREATEDBY   VARCHAR2(1)  NOT NULL
  ,MODIFIEDON  DATE NOT NULL
  ,MODIFIEDBY  VARCHAR2(1)  NOT NULL
);
ALTER TABLE MENUITEM_TRL ADD CONSTRAINT PK_MENUITEMTRL PRIMARY KEY (ID);
ALTER TABLE MENUITEM_TRL ADD CONSTRAINT UK_MENUITEMTRL UNIQUE (MENUITEM_ID,LANG);

prompt Creating table MENU_SHORTCUT...

CREATE TABLE MENU_SHORTCUT (
   ID           NUMBER(1)  NOT NULL
  ,OWNER        VARCHAR2(1)  NOT NULL
  ,TITLE        VARCHAR2(1)  NOT NULL
  ,LINK         VARCHAR2(1) 
  ,MENUITEM_ID  NUMBER(1) 
  ,MENUSHRCT_ID NUMBER(1) 
  ,POSITION     NUMBER(1)  NOT NULL
  ,CREATEDON    DATE NOT NULL
  ,CREATEDBY    VARCHAR2(1)  NOT NULL
  ,MODIFIEDON   DATE NOT NULL
  ,MODIFIEDBY   VARCHAR2(1)  NOT NULL
);
ALTER TABLE MENU_SHORTCUT ADD CONSTRAINT PK_MENUSHRCT PRIMARY KEY (ID);

prompt Creating table PARCEL...

CREATE TABLE PARCEL (
   ID                        NUMBER(1)  NOT NULL
  ,CODE                      VARCHAR2(1)  NOT NULL
  ,CLIENT_ID                 NUMBER(1)  NOT NULL
  ,EXP_BPARTNER_ID           NUMBER(1) 
  ,EXP_NAME                  VARCHAR2(1) 
  ,EXP_BPADRESS_ID           NUMBER(1) 
  ,EXP_BPADRESS              VARCHAR2(1) 
  ,EXP_COUNTRY               VARCHAR2(1) 
  ,EXP_REGION                VARCHAR2(1) 
  ,EXP_CITY                  VARCHAR2(1) 
  ,EXP_CITY_ID               NUMBER(1) 
  ,EXP_ZIP                   VARCHAR2(1) 
  ,EXP_ADRESS_NOTE           VARCHAR2(1) 
  ,DEST_BPARTNER_ID          NUMBER(1) 
  ,DEST_NAME                 VARCHAR2(1) 
  ,DEST_BPADRESS_ID          NUMBER(1) 
  ,DEST_BPADRESS             VARCHAR2(1) 
  ,DEST_COUNTRY              VARCHAR2(1) 
  ,DEST_REGION               VARCHAR2(1) 
  ,DEST_CITY                 VARCHAR2(1) 
  ,DEST_CITY_ID              NUMBER(1) 
  ,DEST_ZIP                  VARCHAR2(1) 
  ,DEST_ADRESS_NOTE          VARCHAR2(1) 
  ,PICKEDUP                  CHAR(1)
  ,PICKUP_MODE               VARCHAR2(1) 
  ,PICKUP_DATE               DATE
  ,PICKUP_AGENT_CODE         VARCHAR2(1) 
  ,DELIVERED                 CHAR(1)
  ,DELIVERY_MODE             VARCHAR2(1) 
  ,DELIVERY_DATE             DATE
  ,DELIVERY_AGENT_CODE       VARCHAR2(1) 
  ,DELIVERED_TO_NAME         VARCHAR2(1) 
  ,DELIVERED_TO_IDENT        VARCHAR2(1) 
  ,REJECTED                  CHAR(1)
  ,REJECT_DATE               DATE
  ,REJECT_REASON             VARCHAR2(1) 
  ,REJECTED_BY_NAME          VARCHAR2(1) 
  ,REJECTED_BY_IDENT         VARCHAR2(1) 
  ,PACKAGE_COUNT             NUMBER(1) 
  ,CONTENT                   VARCHAR2(1) 
  ,NOTES                     VARCHAR2(1) 
  ,DECLARED_VALUE            NUMBER(1) 
  ,INSURED_VALUE             NUMBER(1) 
  ,REF_PARCEL_ID             NUMBER(1) 
  ,REF_PARCEL_REFERENCE_TYPE VARCHAR2(1) 
  ,CREATEDON                 DATE NOT NULL
  ,CREATEDBY                 VARCHAR2(1)  NOT NULL
  ,MODIFIEDON                DATE NOT NULL
  ,MODIFIEDBY                VARCHAR2(1)  NOT NULL
);
ALTER TABLE PARCEL ADD CONSTRAINT PK_PARCEL PRIMARY KEY (ID);
ALTER TABLE PARCEL ADD CONSTRAINT UK_PARCEL UNIQUE (CODE);

prompt Creating table PAYMENT...

CREATE TABLE PAYMENT (
   ID               NUMBER(1)  NOT NULL
  ,CLIENT_ID        NUMBER(1)  NOT NULL
  ,PAYDOCTYPE_CODE  VARCHAR2(1)  NOT NULL
  ,DOC_NO           VARCHAR2(1) 
  ,DOC_DATE         DATE
  ,BPARTNER_FROM    NUMBER(1)  NOT NULL
  ,BPARTNER_TO      NUMBER(1)  NOT NULL
  ,IS_PAYABLE       CHAR(1) NOT NULL
  ,IS_RECEIVABLE    CHAR(1) NOT NULL
  ,AMOUNT           NUMBER(1) 
  ,CURRENCY         VARCHAR2(1) 
  ,NOTES            VARCHAR2(1) 
  ,CREATEDON        DATE NOT NULL
  ,CREATEDBY        VARCHAR2(1)  NOT NULL
  ,MODIFIEDON       DATE NOT NULL
  ,MODIFIEDBY       VARCHAR2(1)  NOT NULL
  ,PAYMNT_ACCT      VARCHAR2(1) 
  ,IS_INSERTED      CHAR(1) NOT NULL
  ,IS_GENERATED     CHAR(1) NOT NULL
  ,IS_APPROVED      CHAR(1) NOT NULL
  ,IS_POSTED        CHAR(1) NOT NULL
  ,ACCDOC_ID        NUMBER(1) 
  ,IS_PREPAYMENT    CHAR(1) NOT NULL
  ,PREPAY_ACCT      VARCHAR2(1) 
  ,RINV_ID          NUMBER(1) 
  ,IS_MULTI_PAYMENT CHAR(1)
  ,IINV_ID          NUMBER(1) 
  ,POSTEDON         DATE
  ,POSTEDBY         VARCHAR2(1) 
);
ALTER TABLE PAYMENT ADD CONSTRAINT PK_PAYMENT PRIMARY KEY (ID);

prompt Creating table PAYMENT_DOCTYPE_ATTR...

CREATE TABLE PAYMENT_DOCTYPE_ATTR (
   ID           NUMBER(1)  NOT NULL
  ,PAYDOCTYP_ID NUMBER(1)  NOT NULL
  ,ACCSCHEMA_ID NUMBER(1)  NOT NULL
  ,ATTR_NAME    VARCHAR2(1)  NOT NULL
  ,ATTR_VALUE   VARCHAR2(1)  NOT NULL
);
ALTER TABLE PAYMENT_DOCTYPE_ATTR ADD CONSTRAINT PK_PAYDOCTYPATT PRIMARY KEY (ID);

prompt Creating table PAYMENT_DOC_TYPE...

CREATE TABLE PAYMENT_DOC_TYPE (
   ID           NUMBER(1)  NOT NULL
  ,CODE         VARCHAR2(1)  NOT NULL
  ,NAME         VARCHAR2(1)  NOT NULL
  ,COMPENSATION CHAR(1) NOT NULL
  ,PAYABLE      CHAR(1) NOT NULL
  ,RECEIVABLE   CHAR(1) NOT NULL
  ,PRINT_REPORT VARCHAR2(1) 
  ,CREATEDON    DATE NOT NULL
  ,CREATEDBY    VARCHAR2(1)  NOT NULL
  ,MODIFIEDON   DATE NOT NULL
  ,MODIFIEDBY   VARCHAR2(1)  NOT NULL
  ,CLIENT_ID    NUMBER(1)  NOT NULL
);
ALTER TABLE PAYMENT_DOC_TYPE ADD CONSTRAINT PK_PAYDOCTYPE PRIMARY KEY (ID);

prompt Creating table PAYMENT_ITEM...

CREATE TABLE PAYMENT_ITEM (
   ID            NUMBER(1)  NOT NULL
  ,CLIENT_ID     NUMBER(1)  NOT NULL
  ,PAYMENT_ID    NUMBER(1)  NOT NULL
  ,AMOUNT        NUMBER(1)  NOT NULL
  ,CURRENCY      VARCHAR2(1)  NOT NULL
  ,ORIG_AMOUNT   NUMBER(1) 
  ,ORIG_CURRENCY VARCHAR2(1) 
  ,DEBIT_CREDIT  CHAR(1) NOT NULL
  ,NOTES         VARCHAR2(1) 
  ,CREATEDON     DATE NOT NULL
  ,CREATEDBY     VARCHAR2(1)  NOT NULL
  ,MODIFIEDON    DATE NOT NULL
  ,MODIFIEDBY    VARCHAR2(1)  NOT NULL
);
ALTER TABLE PAYMENT_ITEM ADD CONSTRAINT PK_PAYITEM PRIMARY KEY (ID);

prompt Creating table PAYMENT_METHOD...

CREATE TABLE PAYMENT_METHOD (
   CODE   VARCHAR2(1)  NOT NULL
  ,NAME   VARCHAR2(1) 
  ,ACTIVE CHAR(1)
);
ALTER TABLE PAYMENT_METHOD ADD CONSTRAINT PK_PAYMETHOD PRIMARY KEY (CODE);

prompt Creating table PAYMENT_TERM_CLASS...

CREATE TABLE PAYMENT_TERM_CLASS (
   CODE      VARCHAR2(1) 
  ,NAME      VARCHAR2(1) 
  ,ACTIVE    CHAR(1)
  ,DAYS_NO   NUMBER(1) 
  ,CLIENT_ID NUMBER(1) 
);

prompt Creating table PERSON...

CREATE TABLE PERSON (
   ID          NUMBER(1)  NOT NULL
  ,BPARTNER_ID NUMBER(1) 
);
ALTER TABLE PERSON ADD CONSTRAINT PK_PERS_ID PRIMARY KEY (ID);

prompt Creating table PRODUCT...

CREATE TABLE PRODUCT (
   ID              NUMBER(1)  NOT NULL
  ,CLIENT_ID       NUMBER(1) 
  ,CODE            VARCHAR2(1)  NOT NULL
  ,NAME            VARCHAR2(1)  NOT NULL
  ,DESCRIPTION     VARCHAR2(1) 
  ,PROD_TYPE       VARCHAR2(1) 
  ,SUMMARY         CHAR(1) NOT NULL
  ,STORABLE        CHAR(1) NOT NULL
  ,CREATEDON       DATE NOT NULL
  ,CREATEDBY       VARCHAR2(1)  NOT NULL
  ,MODIFIEDON      DATE NOT NULL
  ,MODIFIEDBY      VARCHAR2(1)  NOT NULL
  ,UOM_CODE        VARCHAR2(1)  NOT NULL
  ,VOLUME          NUMBER(1) 
  ,WEIGHT          NUMBER(1) 
  ,PRODCATEG_ID    NUMBER(1)  NOT NULL
  ,FOR_SALE        CHAR(1)
  ,EXPENSE_ACCOUNT VARCHAR2(1) 
  ,REVENUE_ACCOUNT VARCHAR2(1) 
);
ALTER TABLE PRODUCT ADD CONSTRAINT PK_PROD PRIMARY KEY (ID);

prompt Creating table PRODUCT_ACCOUNT...

CREATE TABLE PRODUCT_ACCOUNT (
   ID           NUMBER(1)  NOT NULL
  ,CLIENT_ID    NUMBER(1)  NOT NULL
  ,PRODUCT_ID   NUMBER(1)  NOT NULL
  ,REVENUE_ACCT VARCHAR2(1) 
  ,EXPENSE_ACCT VARCHAR2(1) 
  ,ASSET_ACCT   VARCHAR2(1) 
  ,ACCSCHEMA_ID NUMBER(1)  NOT NULL
  ,CREATEDON    DATE NOT NULL
  ,CREATEDBY    VARCHAR2(1)  NOT NULL
  ,MODIFIEDON   DATE NOT NULL
  ,MODIFIEDBY   VARCHAR2(1)  NOT NULL
);
ALTER TABLE PRODUCT_ACCOUNT ADD CONSTRAINT PK_PRODACCT PRIMARY KEY (ID);
ALTER TABLE PRODUCT_ACCOUNT ADD CONSTRAINT UK_PRODACCT UNIQUE (CLIENT_ID,ACCSCHEMA_ID,PRODUCT_ID);

prompt Creating table PRODUCT_CATEGORY...

CREATE TABLE PRODUCT_CATEGORY (
   ID           NUMBER(1)  NOT NULL
  ,CODE         VARCHAR2(1)  NOT NULL
  ,NAME         VARCHAR2(1)  NOT NULL
  ,PRODCATEG_ID NUMBER(1) 
  ,DESCRIPTION  VARCHAR2(1) 
  ,CREATEDON    DATE NOT NULL
  ,CREATEDBY    VARCHAR2(1)  NOT NULL
  ,MODIFIEDON   DATE NOT NULL
  ,MODIFIEDBY   VARCHAR2(1)  NOT NULL
  ,CLIENT_ID    NUMBER(1)  NOT NULL
  ,ACTIVE       CHAR(1) NOT NULL
);
ALTER TABLE PRODUCT_CATEGORY ADD CONSTRAINT PK_PRODCATEG PRIMARY KEY (ID);

prompt Creating table PRODUCT_CATEGORY_ACCOUNT...

CREATE TABLE PRODUCT_CATEGORY_ACCOUNT (
   ID            NUMBER(1)  NOT NULL
  ,PRODCATEG_ID  NUMBER(1)  NOT NULL
  ,CLIENT_ID     NUMBER(1)  NOT NULL
  ,ACCSCHEMA_ID  NUMBER(1)  NOT NULL
  ,ACCOUNT_NAME  VARCHAR2(1)  NOT NULL
  ,ACCOUNT_VALUE VARCHAR2(1)  NOT NULL
  ,CREATEDON     DATE NOT NULL
  ,CREATEDBY     VARCHAR2(1)  NOT NULL
  ,MODIFIEDON    DATE NOT NULL
  ,MODIFIEDBY    VARCHAR2(1)  NOT NULL
  ,ACTIVE        CHAR(1) NOT NULL
);
ALTER TABLE PRODUCT_CATEGORY_ACCOUNT ADD CONSTRAINT PK_PRODCATEGACC PRIMARY KEY (ID);

prompt Creating table PROJECT...

CREATE TABLE PROJECT (
   ID          NUMBER(1)  NOT NULL
  ,NAME        VARCHAR2(1)  NOT NULL
  ,CLIENT_ID   NUMBER(1)  NOT NULL
  ,STATUS_CODE VARCHAR2(1)  NOT NULL
  ,CREATEDON   DATE NOT NULL
  ,CREATEDBY   VARCHAR2(1)  NOT NULL
  ,MODIFIEDON  DATE NOT NULL
  ,MODIFIEDBY  VARCHAR2(1)  NOT NULL
  ,TYPE_CODE   VARCHAR2(1)  NOT NULL
);
ALTER TABLE PROJECT ADD CONSTRAINT PK_PROJECT PRIMARY KEY (ID);

prompt Creating table PROJECT_CMP_TYPE...

CREATE TABLE PROJECT_CMP_TYPE (
   ID         NUMBER(1)  NOT NULL
  ,PROJECT_ID NUMBER(1)  NOT NULL
  ,CODE       VARCHAR2(1)  NOT NULL
  ,NAME       VARCHAR2(1)  NOT NULL
);
ALTER TABLE PROJECT_CMP_TYPE ADD CONSTRAINT PK_PRJCMPTYP PRIMARY KEY (ID);
ALTER TABLE PROJECT_CMP_TYPE ADD CONSTRAINT UK_PRJCMPTYP UNIQUE (PROJECT_ID,CODE);

prompt Creating table PROJECT_ISSUE...

CREATE TABLE PROJECT_ISSUE (
   ID                       NUMBER(1)  NOT NULL
  ,PROJECT_ID               NUMBER(1)  NOT NULL
  ,TITLE                    VARCHAR2(1)  NOT NULL
  ,ISSUE_TYPE_CODE          VARCHAR2(1)  NOT NULL
  ,SEVERITY_CODE            VARCHAR2(1) 
  ,AFF_CMP_TYPE_CODE        VARCHAR2(1) 
  ,AFF_CMP                  VARCHAR2(1) 
  ,AFF_PROJECT_RELEASE_CODE VARCHAR2(1) 
  ,STATUS_CODE              VARCHAR2(1) 
  ,IS_CLOSED                CHAR(1) NOT NULL
  ,DESCRIPTION              VARCHAR2(1) 
  ,CREATEDON                DATE NOT NULL
  ,CREATEDBY                VARCHAR2(1)  NOT NULL
  ,MODIFIEDON               DATE NOT NULL
  ,MODIFIEDBY               VARCHAR2(1)  NOT NULL
  ,PRIORITY_CODE            VARCHAR2(1) 
  ,ASSIGNED_TO              VARCHAR2(1) 
  ,PLAN_STARTDATE           DATE
  ,PLAN_ENDDATE             DATE
  ,ACT_STARTDATE            DATE
  ,ACT_ENDDATE              DATE
  ,ESTIMATE_EFFORT          NUMBER(1) 
  ,ACTUAL_EFFORT            NUMBER(1) 
  ,EFFORT_UNIT              VARCHAR2(1) 
);
ALTER TABLE PROJECT_ISSUE ADD CONSTRAINT PK_PRJISSUE PRIMARY KEY (ID);

prompt Creating table PROJECT_ISSUE_ATTACHMENT...

CREATE TABLE PROJECT_ISSUE_ATTACHMENT (
   ID               NUMBER(1)  NOT NULL
  ,PROJECT_ISSUE_ID NUMBER(1)  NOT NULL
  ,FILE_NAME        VARCHAR2(1)  NOT NULL
  ,CREATEDON        DATE NOT NULL
  ,CREATEDBY        VARCHAR2(1)  NOT NULL
  ,NOTES            VARCHAR2(1) 
);
ALTER TABLE PROJECT_ISSUE_ATTACHMENT ADD CONSTRAINT PK_PRJISSATT PRIMARY KEY (ID);

prompt Creating table PROJECT_ISSUE_CMP_ASSOC...

CREATE TABLE PROJECT_ISSUE_CMP_ASSOC (
   ID               NUMBER(1)  NOT NULL
  ,PROJECT_ISSUE_ID NUMBER(1)  NOT NULL
  ,CMP_NAME         VARCHAR2(1)  NOT NULL
  ,CMP_LOCATION     VARCHAR2(1) 
  ,CMP_VERSION      VARCHAR2(1) 
);
ALTER TABLE PROJECT_ISSUE_CMP_ASSOC ADD CONSTRAINT PK_PRJISSCMPASC PRIMARY KEY (ID);

prompt Creating table PROJECT_ISSUE_NOTE...

CREATE TABLE PROJECT_ISSUE_NOTE (
   ID               NUMBER(1)  NOT NULL
  ,PROJECT_ISSUE_ID NUMBER(1)  NOT NULL
  ,NOTE             VARCHAR2(1)  NOT NULL
  ,CREATEDBY        VARCHAR2(1)  NOT NULL
  ,CREATEDON        DATE NOT NULL
  ,MODIFIEDBY       VARCHAR2(1)  NOT NULL
  ,MODIFIEDON       DATE NOT NULL
);
ALTER TABLE PROJECT_ISSUE_NOTE ADD CONSTRAINT PK_PRJISSNOTE PRIMARY KEY (ID);

prompt Creating table PROJECT_ISSUE_PRIORITY...

CREATE TABLE PROJECT_ISSUE_PRIORITY (
   ID   NUMBER(1)  NOT NULL
  ,CODE VARCHAR2(1)  NOT NULL
  ,NAME VARCHAR2(1)  NOT NULL
);
ALTER TABLE PROJECT_ISSUE_PRIORITY ADD CONSTRAINT PK_PRJISSPRI PRIMARY KEY (ID);
ALTER TABLE PROJECT_ISSUE_PRIORITY ADD CONSTRAINT UK_PRJISSPRI UNIQUE (CODE);

prompt Creating table PROJECT_ISSUE_SEVERITY...

CREATE TABLE PROJECT_ISSUE_SEVERITY (
   ID   NUMBER(1)  NOT NULL
  ,CODE VARCHAR2(1)  NOT NULL
  ,NAME VARCHAR2(1)  NOT NULL
);
ALTER TABLE PROJECT_ISSUE_SEVERITY ADD CONSTRAINT PK_PRJISSSEV PRIMARY KEY (ID);
ALTER TABLE PROJECT_ISSUE_SEVERITY ADD CONSTRAINT UK_PRJISSSEV UNIQUE (CODE);

prompt Creating table PROJECT_ISSUE_STATUS...

CREATE TABLE PROJECT_ISSUE_STATUS (
   ID   NUMBER(1)  NOT NULL
  ,CODE VARCHAR2(1)  NOT NULL
  ,NAME VARCHAR2(1)  NOT NULL
);
ALTER TABLE PROJECT_ISSUE_STATUS ADD CONSTRAINT PK_PRJISSSTS PRIMARY KEY (ID);
ALTER TABLE PROJECT_ISSUE_STATUS ADD CONSTRAINT UK_PRJISSSTS UNIQUE (CODE);

prompt Creating table PROJECT_ISSUE_TYPE...

CREATE TABLE PROJECT_ISSUE_TYPE (
   ID   NUMBER(1)  NOT NULL
  ,CODE VARCHAR2(1)  NOT NULL
  ,NAME VARCHAR2(1)  NOT NULL
);
ALTER TABLE PROJECT_ISSUE_TYPE ADD CONSTRAINT PK_PRJISSTYP PRIMARY KEY (ID);
ALTER TABLE PROJECT_ISSUE_TYPE ADD CONSTRAINT UK_PRJISSTYP UNIQUE (CODE);

prompt Creating table PROJECT_STATUS...

CREATE TABLE PROJECT_STATUS (
   ID   NUMBER(1)  NOT NULL
  ,CODE VARCHAR2(1)  NOT NULL
  ,NAME VARCHAR2(1)  NOT NULL
);
ALTER TABLE PROJECT_STATUS ADD CONSTRAINT PK_PRJSTS PRIMARY KEY (ID);
ALTER TABLE PROJECT_STATUS ADD CONSTRAINT UK_PRJSTS UNIQUE (CODE);

prompt Creating table PROJECT_TYPE...

CREATE TABLE PROJECT_TYPE (
   ID   NUMBER(1)  NOT NULL
  ,CODE VARCHAR2(1)  NOT NULL
  ,NAME VARCHAR2(1)  NOT NULL
);
ALTER TABLE PROJECT_TYPE ADD CONSTRAINT PK_PRJTYPE PRIMARY KEY (ID);
ALTER TABLE PROJECT_TYPE ADD CONSTRAINT UK_PRJTYPE UNIQUE (CODE);

prompt Creating table PURCHASE_NEED...

CREATE TABLE PURCHASE_NEED (
   ID         NUMBER(1)  NOT NULL
  ,DOC_DATE   DATE NOT NULL
  ,DOC_NO     VARCHAR2(1)  NOT NULL
  ,CLIENT_ID  NUMBER(1) 
  ,CREATEDON  DATE
  ,CREATEDBY  VARCHAR2(1) 
  ,MODIFIEDON DATE
  ,MODIFIEDBY VARCHAR2(1) 
  ,TITLE      VARCHAR2(1) 
);
ALTER TABLE PURCHASE_NEED ADD CONSTRAINT PK_PNEED PRIMARY KEY (ID);

prompt Creating table PURCHASE_NEED_LINE...

CREATE TABLE PURCHASE_NEED_LINE (
   ID       NUMBER(1)  NOT NULL
  ,PNEED_ID NUMBER(1)  NOT NULL
  ,POSITION NUMBER(1)  NOT NULL
  ,PROD_ID  NUMBER(1) 
  ,NOTES    VARCHAR2(1) 
  ,QTY      NUMBER(1) 
  ,UOM_CODE VARCHAR2(1) 
);
ALTER TABLE PURCHASE_NEED_LINE ADD CONSTRAINT PK_PNEEDLIN PRIMARY KEY (ID);

prompt Creating table PURCHASE_ORDER...

CREATE TABLE PURCHASE_ORDER (
   ID                  NUMBER(1)  NOT NULL
  ,DOC_NO              VARCHAR2(1)  NOT NULL
  ,DOC_DATE            DATE NOT NULL
  ,CLIENT_ID           NUMBER(1)  NOT NULL
  ,BPARTNER_ID         NUMBER(1)  NOT NULL
  ,BPARTNER_CONTACT_ID NUMBER(1) 
  ,REF_PORDER_ID       NUMBER(1) 
  ,CURRENCY            VARCHAR2(1)  NOT NULL
  ,TOTAL_AMOUNT        NUMBER(1)  NOT NULL
  ,CREATEDON           DATE NOT NULL
  ,CREATEDBY           VARCHAR2(1)  NOT NULL
  ,MODIFIEDON          DATE NOT NULL
  ,MODIFIEDBY          VARCHAR2(1)  NOT NULL
);
ALTER TABLE PURCHASE_ORDER ADD CONSTRAINT PK_PORDER PRIMARY KEY (ID);

prompt Creating table PURCHASE_ORDER_LINE...

CREATE TABLE PURCHASE_ORDER_LINE (
   ID             NUMBER(1)  NOT NULL
  ,PORDER_ID      NUMBER(1)  NOT NULL
  ,LINE_NR        NUMBER(1)  NOT NULL
  ,PRODUCT_ID     NUMBER(1) 
  ,QTY            NUMBER(1)  NOT NULL
  ,UOM_CODE       VARCHAR2(1)  NOT NULL
  ,PRICE          NUMBER(1)  NOT NULL
  ,NET_AMOUNT     NUMBER(1)  NOT NULL
  ,CURRENCY_CODE  VARCHAR2(1) 
  ,NOTES          VARCHAR2(1) 
  ,DATE_REQUESTED DATE
  ,DATE_PROMISED  DATE
  ,DATE_DELIVERED DATE
  ,CREATEDON      DATE NOT NULL
  ,CREATEDBY      VARCHAR2(1)  NOT NULL
  ,MODIFIEDON     DATE NOT NULL
  ,MODIFIEDBY     VARCHAR2(1)  NOT NULL
);
ALTER TABLE PURCHASE_ORDER_LINE ADD CONSTRAINT PK_PORDLIN PRIMARY KEY (ID);

prompt Creating table REGION...

CREATE TABLE REGION (
   ID           NUMBER(1)  NOT NULL
  ,CODE         VARCHAR2(1)  NOT NULL
  ,NAME         VARCHAR2(1)  NOT NULL
  ,COUNTRY_CODE VARCHAR2(1)  NOT NULL
  ,ACTIVE       CHAR(1) NOT NULL
  ,WITH_CITIES  CHAR(1) NOT NULL
  ,ISO          VARCHAR2(1) 
);
ALTER TABLE REGION ADD CONSTRAINT PK_REGION PRIMARY KEY (ID);
ALTER TABLE REGION ADD CONSTRAINT UK_REGION UNIQUE (COUNTRY_CODE,CODE);

prompt Creating table REPORTING_PERIOD...

CREATE TABLE REPORTING_PERIOD (
   ID NUMBER(1)  NOT NULL
);
ALTER TABLE REPORTING_PERIOD ADD CONSTRAINT PK_REPPERIOD PRIMARY KEY (ID);

prompt Creating table RINVOICE...

CREATE TABLE RINVOICE (
   ID               NUMBER(1)  NOT NULL
  ,DOC_NO           VARCHAR2(1)  NOT NULL
  ,DOC_DATE         DATE NOT NULL
  ,CLIENT_ID        NUMBER(1)  NOT NULL
  ,DOC_TYPE         VARCHAR2(1)  NOT NULL
  ,DOC_CURRENCY     VARCHAR2(1)  NOT NULL
  ,TOTAL_NET_AMOUNT NUMBER(1)  NOT NULL
  ,TOTAL_TAX_AMOUNT NUMBER(1)  NOT NULL
  ,TOTAL_AMOUNT     NUMBER(1)  NOT NULL
  ,CREATEDON        DATE NOT NULL
  ,CREATEDBY        VARCHAR2(1)  NOT NULL
  ,MODIFIEDON       DATE NOT NULL
  ,MODIFIEDBY       VARCHAR2(1)  NOT NULL
  ,ISSUER_ID        NUMBER(1)  NOT NULL
  ,RECEIVER_ID      NUMBER(1)  NOT NULL
  ,DUE_DATE         DATE
  ,IS_INSERTED      CHAR(1) NOT NULL
  ,IS_PAYABLE       CHAR(1) NOT NULL
  ,IS_PAYED         CHAR(1) NOT NULL
  ,IS_POSTED        CHAR(1) NOT NULL
  ,ACCT             VARCHAR2(1)  NOT NULL
  ,POSTEDON         DATE
  ,POSTEDBY         VARCHAR2(1) 
  ,ACCDOC_ID        NUMBER(1) 
  ,REF_RINVOICE_ID  NUMBER(1) 
  ,NOTES            VARCHAR2(1) 
  ,INSERTEDBY       VARCHAR2(1) 
  ,INSERTEDON       DATE
);
ALTER TABLE RINVOICE ADD CONSTRAINT PK_RINV PRIMARY KEY (ID);

prompt Creating table RINVOICE_ITEM...

CREATE TABLE RINVOICE_ITEM (
   ID             NUMBER(1)  NOT NULL
  ,RINV_ID        NUMBER(1)  NOT NULL
  ,PROD_ID        NUMBER(1) 
  ,QUANTITY       NUMBER(1) 
  ,QUANTITY_UNIT  VARCHAR2(1) 
  ,NET_AMOUNT     NUMBER(1)  NOT NULL
  ,PRICE          NUMBER(1) 
  ,CREATEDON      DATE NOT NULL
  ,CREATEDBY      VARCHAR2(1)  NOT NULL
  ,MODIFIEDON     DATE NOT NULL
  ,MODIFIEDBY     VARCHAR2(1)  NOT NULL
  ,RINVITEM_ID    NUMBER(1) 
  ,NOTES          VARCHAR2(1) 
  ,TAX_ID         NUMBER(1) 
  ,TAX_RATE       NUMBER(1) 
  ,TAX_AMOUNT     NUMBER(1) 
  ,CURRENCY       VARCHAR2(1) 
  ,CURRENCY_XRATE NUMBER(1) 
  ,PURCHASE_ACCT  VARCHAR2(1)  NOT NULL
  ,ORIG_AMOUNT    NUMBER(1) 
  ,ORIG_CURRENCY  VARCHAR2(1) 
  ,TAX_AMOUNT_NR  NUMBER(1) 
);
ALTER TABLE RINVOICE_ITEM ADD CONSTRAINT PK_RINVITEM PRIMARY KEY (ID);

prompt Creating table RINV_DOCTYP_ATTR...

CREATE TABLE RINV_DOCTYP_ATTR (
   ID            NUMBER(1)  NOT NULL
  ,RINVDOCTYP_ID NUMBER(1)  NOT NULL
  ,ACCSCHEMA_ID  NUMBER(1)  NOT NULL
  ,ATTR_NAME     VARCHAR2(1)  NOT NULL
  ,ATTR_VALUE    VARCHAR2(1) 
);
ALTER TABLE RINV_DOCTYP_ATTR ADD CONSTRAINT PK_RINVDOCTYPATT PRIMARY KEY (ID);

prompt Creating table RINV_DOC_TYPE...

CREATE TABLE RINV_DOC_TYPE (
   ID         NUMBER(1)  NOT NULL
  ,CODE       VARCHAR2(1)  NOT NULL
  ,NAME       VARCHAR2(1)  NOT NULL
  ,ACTIVE     CHAR(1) NOT NULL
  ,CLIENT_ID  NUMBER(1)  NOT NULL
  ,CREATEDON  DATE NOT NULL
  ,CREATEDBY  VARCHAR2(1)  NOT NULL
  ,MODIFIEDON DATE NOT NULL
  ,MODIFIEDBY VARCHAR2(1)  NOT NULL
);
ALTER TABLE RINV_DOC_TYPE ADD CONSTRAINT PK_RINVDOCTYPE PRIMARY KEY (ID);
ALTER TABLE RINV_DOC_TYPE ADD CONSTRAINT UK_RINVDOCTYPE UNIQUE (CODE);

prompt Creating table SALES_ORDER...

CREATE TABLE SALES_ORDER (
   ID                        NUMBER(1)  NOT NULL
  ,DOC_NO                    VARCHAR2(1)  NOT NULL
  ,DOC_DATE                  DATE NOT NULL
  ,CLIENT_ID                 NUMBER(1) 
  ,CREATEDON                 DATE NOT NULL
  ,CREATEDBY                 VARCHAR2(1)  NOT NULL
  ,MODIFIEDON                DATE NOT NULL
  ,MODIFIEDBY                VARCHAR2(1)  NOT NULL
  ,BPARTNER_ID               NUMBER(1)  NOT NULL
  ,BILL_BPARTNER_ID          NUMBER(1) 
  ,DELIV_BPARTNER_ID         NUMBER(1) 
  ,PAY_BPARTNER_ID           NUMBER(1) 
  ,BPARTNER_CONTACT_ID       NUMBER(1) 
  ,BILL_BPARTNER_CONTACT_ID  NUMBER(1) 
  ,DELIV_BPARTNER_CONTACT_ID NUMBER(1) 
  ,PAY_BPARTNER_CONTACT_ID   NUMBER(1) 
  ,REF_SORDER_ID             NUMBER(1) 
  ,CURRENCY                  VARCHAR2(1)  NOT NULL
  ,PAYMETHOD_CODE            VARCHAR2(1) 
  ,SALESREP_ID               NUMBER(1) 
  ,TOTAL_AMOUNT              NUMBER(1)  NOT NULL
);
ALTER TABLE SALES_ORDER ADD CONSTRAINT PK_SORDER PRIMARY KEY (ID);

prompt Creating table SALES_ORDER_LINE...

CREATE TABLE SALES_ORDER_LINE (
   ID             NUMBER(1)  NOT NULL
  ,SORDER_ID      NUMBER(1)  NOT NULL
  ,CREATEDON      DATE NOT NULL
  ,CREATEDBY      VARCHAR2(1)  NOT NULL
  ,MODIFIEDON     DATE NOT NULL
  ,MODIFIEDBY     VARCHAR2(1)  NOT NULL
  ,LINE_NR        NUMBER(1)  NOT NULL
  ,PRODUCT_ID     NUMBER(1) 
  ,QTY_ORDERED    NUMBER(1)  NOT NULL
  ,QTY            NUMBER(1)  NOT NULL
  ,QTY_INVOICED   NUMBER(1)  NOT NULL
  ,QTY_DELIVERED  NUMBER(1)  NOT NULL
  ,QTY_RESERVED   NUMBER(1)  NOT NULL
  ,UOM_CODE       VARCHAR2(1)  NOT NULL
  ,PRICE          NUMBER(1)  NOT NULL
  ,DISCOUNT       NUMBER(1)  NOT NULL
  ,DISCOUNT_TYPE  CHAR(1) NOT NULL
  ,CURRENCY_CODE  VARCHAR2(1) 
  ,NOTES          VARCHAR2(1) 
  ,DATE_REQUESTED DATE
  ,DATE_PROMISED  DATE
  ,DATE_DELIVERED DATE
  ,NET_AMOUNT     NUMBER(1)  NOT NULL
  ,RAW_NET_AMOUNT NUMBER(1)  NOT NULL
);
ALTER TABLE SALES_ORDER_LINE ADD CONSTRAINT PK_SORDLIN PRIMARY KEY (ID);

prompt Creating table SERVER_MESSAGE...

CREATE TABLE SERVER_MESSAGE (
   ID   NUMBER(1)  NOT NULL
  ,CODE VARCHAR2(1)  NOT NULL
);
ALTER TABLE SERVER_MESSAGE ADD CONSTRAINT PK_SRVMSG PRIMARY KEY (ID);
ALTER TABLE SERVER_MESSAGE ADD CONSTRAINT UK_SRVMSG UNIQUE (CODE);

prompt Creating table SERVER_MESSAGE_TRL...

CREATE TABLE SERVER_MESSAGE_TRL (
   ID          NUMBER(1)  NOT NULL
  ,SRVMSG_CODE VARCHAR2(1)  NOT NULL
  ,LANG_CODE   VARCHAR2(1)  NOT NULL
  ,TRANSLATION VARCHAR2(1)  NOT NULL
  ,MODIFIEDON  DATE NOT NULL
  ,MODIFIEDBY  VARCHAR2(1)  NOT NULL
);
ALTER TABLE SERVER_MESSAGE_TRL ADD CONSTRAINT PK_SRVMSGTRL PRIMARY KEY (ID);
ALTER TABLE SERVER_MESSAGE_TRL ADD CONSTRAINT UK_SRVMSGTRL UNIQUE (SRVMSG_CODE,LANG_CODE);

prompt Creating table STREET...

CREATE TABLE STREET (
   ID           NUMBER(1)  NOT NULL
  ,COUNTRY_CODE VARCHAR2(1)  NOT NULL
  ,REGION_CODE  VARCHAR2(1)  NOT NULL
  ,CITY_ID      NUMBER(1)  NOT NULL
  ,NAME         VARCHAR2(1)  NOT NULL
  ,ACTIVE       VARCHAR2(1)  NOT NULL
  ,CREATEDON    DATE NOT NULL
  ,CREATEDBY    VARCHAR2(1)  NOT NULL
  ,MODIFIEDON   DATE NOT NULL
  ,MODIFIEDBY   VARCHAR2(1)  NOT NULL
);
ALTER TABLE STREET ADD CONSTRAINT PK_STREET PRIMARY KEY (ID);

prompt Creating table SUBSCRIPTION...

CREATE TABLE SUBSCRIPTION (
   ID        NUMBER(1)  NOT NULL
  ,CODE      VARCHAR2(1) 
  ,NAME      VARCHAR2(1) 
  ,CLIENT_ID NUMBER(1) 
);
ALTER TABLE SUBSCRIPTION ADD CONSTRAINT PK_SUBSC PRIMARY KEY (ID);

prompt Creating table SYS_PARAM...

CREATE TABLE SYS_PARAM (
   ID               NUMBER(1)  NOT NULL
  ,CODE             VARCHAR2(1)  NOT NULL
  ,NAME             VARCHAR2(1)  NOT NULL
  ,DESCRIPTION      VARCHAR2(1)  NOT NULL
  ,SYSPARAMGRP_CODE VARCHAR2(1)  NOT NULL
  ,CREATEDON        DATE NOT NULL
  ,CREATEDBY        VARCHAR2(1)  NOT NULL
  ,MODIFIEDON       DATE NOT NULL
  ,MODIFIEDBY       VARCHAR2(1)  NOT NULL
);
ALTER TABLE SYS_PARAM ADD CONSTRAINT PK_SYSPARAM PRIMARY KEY (ID);
ALTER TABLE SYS_PARAM ADD CONSTRAINT UK_SYSPARAM UNIQUE (CODE);

prompt Creating table SYS_PARAM_GROUP...

CREATE TABLE SYS_PARAM_GROUP (
   CODE VARCHAR2(1)  NOT NULL
  ,NAME VARCHAR2(1)  NOT NULL
);
ALTER TABLE SYS_PARAM_GROUP ADD CONSTRAINT UK_SYSPARAMGRP PRIMARY KEY (CODE);

prompt Creating table SYS_PARAM_VALID_VALUE...

CREATE TABLE SYS_PARAM_VALID_VALUE (
   ID         NUMBER(1)  NOT NULL
  ,PARAM_CODE VARCHAR2(1)  NOT NULL
  ,VALUE      VARCHAR2(1)  NOT NULL
  ,NOTES      VARCHAR2(1)  NOT NULL
);
ALTER TABLE SYS_PARAM_VALID_VALUE ADD CONSTRAINT PK_PARAMVLDVAL PRIMARY KEY (ID);
ALTER TABLE SYS_PARAM_VALID_VALUE ADD CONSTRAINT UK_PARAMVLDVAL UNIQUE (PARAM_CODE,VALUE);

prompt Creating table SYS_PARAM_VALUE...

CREATE TABLE SYS_PARAM_VALUE (
   ID          NUMBER(1)  NOT NULL
  ,CLIENT_ID   NUMBER(1)  NOT NULL
  ,PARAM_CODE  VARCHAR2(1)  NOT NULL
  ,PARAM_VALUE VARCHAR2(1) 
  ,MODIFIEDON  DATE NOT NULL
  ,MODIFIEDBY  VARCHAR2(1)  NOT NULL
);
ALTER TABLE SYS_PARAM_VALUE ADD CONSTRAINT PK_SYSPRMVAL PRIMARY KEY (ID);
ALTER TABLE SYS_PARAM_VALUE ADD CONSTRAINT UK_SYSPRMVAL UNIQUE (CLIENT_ID,PARAM_CODE);

prompt Creating table SYS_ROLE...

CREATE TABLE SYS_ROLE (
   ID          NUMBER(1)  NOT NULL
  ,NAME        VARCHAR2(1)  NOT NULL
  ,DESCRIPTION VARCHAR2(1) 
  ,CREATEDON   DATE NOT NULL
  ,CREATEDBY   VARCHAR2(1)  NOT NULL
  ,MODIFIEDON  DATE NOT NULL
  ,MODIFIEDBY  VARCHAR2(1)  NOT NULL
);
ALTER TABLE SYS_ROLE ADD CONSTRAINT PK_ROLE PRIMARY KEY (ID);
ALTER TABLE SYS_ROLE ADD CONSTRAINT UK_ROLE UNIQUE (NAME);

prompt Creating table SYS_USER...

CREATE TABLE SYS_USER (
   ID              NUMBER(1)  NOT NULL
  ,LOGIN_CODE      VARCHAR2(1)  NOT NULL
  ,LOGIN_PASSWORD  VARCHAR2(1) 
  ,PERSON_ID       NUMBER(1) 
  ,ACCOUNT_LOCKED  CHAR(1) NOT NULL
  ,ACCOUNT_EXPIRED CHAR(1) NOT NULL
  ,CREATEDON       DATE NOT NULL
  ,CREATEDBY       VARCHAR2(1)  NOT NULL
  ,MODIFIEDON      DATE NOT NULL
  ,MODIFIEDBY      VARCHAR2(1)  NOT NULL
  ,DBUSER          VARCHAR2(1) 
);
ALTER TABLE SYS_USER ADD CONSTRAINT PK_USER PRIMARY KEY (ID);

prompt Creating table SYS_USER_DOCSERRNG...

CREATE TABLE SYS_USER_DOCSERRNG (
   ID           NUMBER(1)  NOT NULL
  ,GRANTED_TO   VARCHAR2(1)  NOT NULL
  ,DOCSERRNG_ID NUMBER(1)  NOT NULL
);
ALTER TABLE SYS_USER_DOCSERRNG ADD CONSTRAINT PK_USRDOCSERRNG PRIMARY KEY (ID);
ALTER TABLE SYS_USER_DOCSERRNG ADD CONSTRAINT UK_USRDOCSERRNG UNIQUE (DOCSERRNG_ID,GRANTED_TO);

prompt Creating table SYS_USER_LOGIN...

CREATE TABLE SYS_USER_LOGIN (
   ID        NUMBER(1)  NOT NULL
  ,USERNAME  VARCHAR2(1)  NOT NULL
  ,LOGIN     DATE NOT NULL
  ,LOGOUT    DATE
  ,IP_ADRESS VARCHAR2(1)  NOT NULL
);
ALTER TABLE SYS_USER_LOGIN ADD CONSTRAINT PK_USRLOG PRIMARY KEY (ID);

prompt Creating table SYS_USER_ROLE...

CREATE TABLE SYS_USER_ROLE (
   ID        NUMBER(1)  NOT NULL
  ,USER_ID   NUMBER(1)  NOT NULL
  ,ROLE_NAME VARCHAR2(1)  NOT NULL
  ,CREATEDON DATE NOT NULL
  ,CREATEDBY VARCHAR2(1)  NOT NULL
);
ALTER TABLE SYS_USER_ROLE ADD CONSTRAINT PK_USRROL PRIMARY KEY (ID);
ALTER TABLE SYS_USER_ROLE ADD CONSTRAINT UK_USRROL UNIQUE (USER_ID,ROLE_NAME);

prompt Creating table TASKS...

CREATE TABLE TASKS (
   ID          NUMBER(1)  NOT NULL
  ,TITLE       VARCHAR2(1) 
  ,FINISH_DATE DATE
  ,START_DATE  DATE
  ,STATUS      VARCHAR2(1) 
  ,ASSIGNED_TO VARCHAR2(1) 
  ,CREATEDON   DATE
  ,CREATEDBY   VARCHAR2(1) 
  ,MODIFIEDON  DATE
  ,MODIFIEDBY  VARCHAR2(1) 
  ,NOTES       VARCHAR2(1) 
  ,CLOSED      CHAR(1)
);
ALTER TABLE TASKS ADD CONSTRAINT PK_TASK PRIMARY KEY (ID);

prompt Creating table TAX...

CREATE TABLE TAX (
   ID                NUMBER(1)  NOT NULL
  ,CLIENT_ID         NUMBER(1)  NOT NULL
  ,TAXTYPE_CODE      VARCHAR2(1)  NOT NULL
  ,VALUE_TYPE        VARCHAR2(1) 
  ,VALUE             NUMBER(1)  NOT NULL
  ,ACTIVE            CHAR(1) NOT NULL
  ,DEFAULT_VALUE     CHAR(1)
  ,NAME              VARCHAR2(1)  NOT NULL
  ,PAYED_REFUND_ACCT VARCHAR2(1) 
  ,COLLECT_ACCT      VARCHAR2(1) 
);
ALTER TABLE TAX ADD CONSTRAINT PK_TAX PRIMARY KEY (ID);

prompt Creating table TAX_TYPE...

CREATE TABLE TAX_TYPE (
   CODE      VARCHAR2(1)  NOT NULL
  ,NAME      VARCHAR2(1)  NOT NULL
  ,NOTES     VARCHAR2(1) 
  ,ACTIVE    CHAR(1) NOT NULL
  ,IS_SYSTEM CHAR(1) NOT NULL
);
ALTER TABLE TAX_TYPE ADD CONSTRAINT PK_TAXTYPE PRIMARY KEY (CODE);

prompt Creating table TEST...

CREATE TABLE TEST (
   ID       NUMBER(1)  NOT NULL
  ,COLUMN_1 VARCHAR2(1)  NOT NULL
);
ALTER TABLE TEST ADD CONSTRAINT PK_TEST PRIMARY KEY (ID);

prompt Creating table TIMESHEET...

CREATE TABLE TIMESHEET (
   ID               NUMBER(1)  NOT NULL
  ,CLIENT_ID        NUMBER(1)  NOT NULL
  ,CHARGED_DATE     DATE NOT NULL
  ,USER_ACCOUNT     VARCHAR2(1)  NOT NULL
  ,EFFORT           NUMBER(1)  NOT NULL
  ,IS_INSERTED      CHAR(1) NOT NULL
  ,IS_APPROVED      CHAR(1) NOT NULL
  ,IS_POSTED        CHAR(1) NOT NULL
  ,CREATEDON        DATE NOT NULL
  ,CREATEDBY        VARCHAR2(1)  NOT NULL
  ,MODIFIEDON       DATE NOT NULL
  ,MODIFIEDBY       VARCHAR2(1)  NOT NULL
  ,POSTEDON         DATE
  ,POSTEDBY         VARCHAR2(1) 
  ,PROJECT_ISSUE_ID NUMBER(1) 
  ,EFFORT_UNIT      VARCHAR2(1)  NOT NULL
);
ALTER TABLE TIMESHEET ADD CONSTRAINT PK_TIMESHT PRIMARY KEY (ID);

prompt Creating table UI_DC...

CREATE TABLE UI_DC (
   ID           NUMBER(1)  NOT NULL
  ,CODE         VARCHAR2(1)  NOT NULL
  ,NAME         VARCHAR2(1)  NOT NULL
  ,NBS_STANDARD CHAR(1)
  ,USER_BUILD   CHAR(1)
  ,DEPRECATED   CHAR(1)
  ,DESCRIPTION  VARCHAR2(1) 
  ,CREATEDON    DATE
  ,CREATEDBY    VARCHAR2(1) 
  ,MODIFIEDON   DATE
  ,MODIFIEDBY   VARCHAR2(1) 
);
ALTER TABLE UI_DC ADD CONSTRAINT PK_UIDC PRIMARY KEY (ID);
ALTER TABLE UI_DC ADD CONSTRAINT UK_UIDC UNIQUE (CODE);

prompt Creating table UI_DC_FIELD...

CREATE TABLE UI_DC_FIELD (
   ID          NUMBER(1)  NOT NULL
  ,UIDC_CODE   VARCHAR2(1)  NOT NULL
  ,FIELD_NAME  VARCHAR2(1)  NOT NULL
  ,DESCRIPTION VARCHAR2(1) 
  ,CREATEDON   DATE NOT NULL
  ,CREATEDBY   VARCHAR2(1)  NOT NULL
  ,MODIFIEDON  DATE NOT NULL
  ,MODIFIEDBY  VARCHAR2(1)  NOT NULL
);
ALTER TABLE UI_DC_FIELD ADD CONSTRAINT PK_UIDCFIELD PRIMARY KEY (ID);
ALTER TABLE UI_DC_FIELD ADD CONSTRAINT UK_UIDCFIELD UNIQUE (UIDC_CODE,FIELD_NAME);

prompt Creating table UI_DC_FIELD_INITVAL...

CREATE TABLE UI_DC_FIELD_INITVAL (
   ID            NUMBER(1)  NOT NULL
  ,UIDC_CODE     VARCHAR2(1)  NOT NULL
  ,FIELD_NAME    VARCHAR2(1)  NOT NULL
  ,FIELD_VALUE   VARCHAR2(1)  NOT NULL
  ,VALUE_TYPE    VARCHAR2(1)  NOT NULL
  ,CREATEDON     DATE NOT NULL
  ,CREATEDBY     VARCHAR2(1)  NOT NULL
  ,MODIFIEDON    DATE NOT NULL
  ,MODIFIEDBY    VARCHAR2(1)  NOT NULL
  ,ACTIVE        CHAR(1) NOT NULL
  ,APPLY_TO_USER VARCHAR2(1) 
);
ALTER TABLE UI_DC_FIELD_INITVAL ADD CONSTRAINT PK_UIFLDINITVAL PRIMARY KEY (ID);
ALTER TABLE UI_DC_FIELD_INITVAL ADD CONSTRAINT UK_UIFLDINITVAL UNIQUE (UIDC_CODE,FIELD_NAME);

prompt Creating table UI_DC_ROLE_PERMISSION...

CREATE TABLE UI_DC_ROLE_PERMISSION (
   ID             NUMBER(1)  NOT NULL
  ,UI_DC          VARCHAR2(1)  NOT NULL
  ,ROLE_NAME      VARCHAR2(1)  NOT NULL
  ,FETCH_ALLOWED  CHAR(1) NOT NULL
  ,INSERT_ALLOWED CHAR(1) NOT NULL
  ,UPDATE_ALLOWED CHAR(1) NOT NULL
  ,DELETE_ALLOWED CHAR(1) NOT NULL
  ,CREATEDON      DATE NOT NULL
  ,CREATEDBY      VARCHAR2(1)  NOT NULL
  ,MODIFIEDON     DATE NOT NULL
  ,MODIFIEDBY     VARCHAR2(1)  NOT NULL
);
ALTER TABLE UI_DC_ROLE_PERMISSION ADD CONSTRAINT PK_UIDCROLEPRMS PRIMARY KEY (ID);
ALTER TABLE UI_DC_ROLE_PERMISSION ADD CONSTRAINT UK_UIDCROLEPRMS UNIQUE (UI_DC,ROLE_NAME);

prompt Creating table UI_DICTIONARY...

CREATE TABLE UI_DICTIONARY (
   ID            NUMBER(1)  NOT NULL
  ,UIDC_CODE     VARCHAR2(1) 
  ,MSG_TYPE      VARCHAR2(1) 
  ,MSG_CODE      VARCHAR2(1) 
  ,MAINTAINED_BY VARCHAR2(1) 
  ,CREATEDON     DATE
  ,CREATEDBY     VARCHAR2(1) 
  ,MODIFIEDON    DATE
  ,MODIFIEDBY    VARCHAR2(1) 
  ,DEFAULT_VALUE VARCHAR2(1) 
);
ALTER TABLE UI_DICTIONARY ADD CONSTRAINT PK_UIDICT PRIMARY KEY (ID);

prompt Creating table UI_DICTIONARY_TRL...

CREATE TABLE UI_DICTIONARY_TRL (
   ID            NUMBER(1)  NOT NULL
  ,UIDICT_ID     NUMBER(1)  NOT NULL
  ,LANGUAGE_CODE VARCHAR2(1)  NOT NULL
  ,TRANSLATION   VARCHAR2(1) 
  ,MODIFIEDON    DATE NOT NULL
  ,MODIFIEDBY    VARCHAR2(1)  NOT NULL
);
ALTER TABLE UI_DICTIONARY_TRL ADD CONSTRAINT PK_UIDICTTRL PRIMARY KEY (ID);

prompt Creating table UI_GUI...

CREATE TABLE UI_GUI (
   ID           NUMBER(1)  NOT NULL
  ,CODE         VARCHAR2(1)  NOT NULL
  ,NAME         VARCHAR2(1)  NOT NULL
  ,NBS_STANDARD CHAR(1) NOT NULL
  ,USER_BUILD   CHAR(1) NOT NULL
  ,CREATEDON    DATE NOT NULL
  ,CREATEDBY    VARCHAR2(1)  NOT NULL
  ,MODIFIEDON   DATE NOT NULL
  ,MODIFIEDBY   VARCHAR2(1)  NOT NULL
  ,DEPRECATED   CHAR(1) NOT NULL
  ,DESCRIPTION  VARCHAR2(1) 
);
ALTER TABLE UI_GUI ADD CONSTRAINT PK_UIGUI PRIMARY KEY (ID);
ALTER TABLE UI_GUI ADD CONSTRAINT UK_UIGUI UNIQUE (CODE);

prompt Creating table UI_LOV...

CREATE TABLE UI_LOV (
   ID           NUMBER(1)  NOT NULL
  ,CODE         VARCHAR2(1) 
  ,NAME         VARCHAR2(1) 
  ,DESCRIPTION  VARCHAR2(1) 
  ,NBS_STANDARD CHAR(1)
  ,USER_BUILD   CHAR(1)
  ,CREATEDON    DATE
  ,CREATEDBY    VARCHAR2(1) 
  ,MODIFIEDON   DATE
  ,MODIFIEDBY   VARCHAR2(1) 
  ,DEPRECATED   CHAR(1)
);
ALTER TABLE UI_LOV ADD CONSTRAINT PK_UILOV PRIMARY KEY (ID);
ALTER TABLE UI_LOV ADD CONSTRAINT UK_UILOV UNIQUE (CODE);

prompt Creating table UOM...

CREATE TABLE UOM (
   ID         NUMBER(1)  NOT NULL
  ,CODE       VARCHAR2(1)  NOT NULL
  ,UOM_TYPE   VARCHAR2(1)  NOT NULL
  ,NAME       VARCHAR2(1)  NOT NULL
  ,CREATEDON  DATE NOT NULL
  ,CREATEDBY  VARCHAR2(1)  NOT NULL
  ,MODIFIEDON DATE NOT NULL
  ,MODIFIEDBY VARCHAR2(1)  NOT NULL
  ,ACTIVE     CHAR(1) NOT NULL
  ,IS_PERIOD  CHAR(1) NOT NULL
  ,IS_VOLUME  CHAR(1) NOT NULL
  ,IS_MASS    CHAR(1) NOT NULL
);
ALTER TABLE UOM ADD CONSTRAINT PK_UOM PRIMARY KEY (ID);
ALTER TABLE UOM ADD CONSTRAINT UK_UOM UNIQUE (CODE);

prompt Creating table UOM_CONVERSION...

CREATE TABLE UOM_CONVERSION (
   ID                NUMBER(1)  NOT NULL
  ,UOM_FROM          VARCHAR2(1)  NOT NULL
  ,UOM_TO            VARCHAR2(1)  NOT NULL
  ,CONVERSION_FACTOR NUMBER(1)  NOT NULL
  ,CREATEDON         DATE
  ,CREATEDBY         VARCHAR2(1) 
  ,MODIFIEDON        DATE
  ,MODIFIEDBY        VARCHAR2(1) 
  ,CONVERSION_TYPE   CHAR(1)
);
ALTER TABLE UOM_CONVERSION ADD CONSTRAINT PK_UOMCONV PRIMARY KEY (ID);
ALTER TABLE UOM_CONVERSION ADD CONSTRAINT UK_UOMCONV UNIQUE (UOM_FROM,UOM_TO);

prompt Creating table UOM_TYPE...

CREATE TABLE UOM_TYPE (
   ID   NUMBER(1)  NOT NULL
  ,CODE VARCHAR2(1)  NOT NULL
  ,NAME VARCHAR2(1)  NOT NULL
);
ALTER TABLE UOM_TYPE ADD CONSTRAINT PK_UOM_TYPE PRIMARY KEY (ID);
ALTER TABLE UOM_TYPE ADD CONSTRAINT UK_UOM_TYPE UNIQUE (CODE);

prompt Creating table USR_DC_LAST_FILTER...

CREATE TABLE USR_DC_LAST_FILTER (
   ID       NUMBER(1)  NOT NULL
  ,USERNAME VARCHAR2(1)  NOT NULL
  ,DC_CODE  VARCHAR2(1)  NOT NULL
);
ALTER TABLE USR_DC_LAST_FILTER ADD CONSTRAINT PK_USRDCLSTFLTR PRIMARY KEY (ID);

prompt Creating table X_IMP_PARCEL...

CREATE TABLE X_IMP_PARCEL (
   ID               NUMBER(1)  NOT NULL
  ,EXP_NAME         VARCHAR2(1) 
  ,EXP_COUNTRY      VARCHAR2(1) 
  ,EXP_REGION       VARCHAR2(1) 
  ,EXP_CITY         VARCHAR2(1) 
  ,EXP_ADRESS       VARCHAR2(1) 
  ,EXP_ZIP          VARCHAR2(1) 
  ,EXP_ADRESS_NOTE  VARCHAR2(1) 
  ,DEST_NAME        VARCHAR2(1) 
  ,DEST_COUNTRY     VARCHAR2(1) 
  ,DEST_REGION      VARCHAR2(1) 
  ,DEST_CITY        VARCHAR2(1) 
  ,DEST_ADRESS      VARCHAR2(1) 
  ,DEST_ZIP         VARCHAR2(1) 
  ,DEST_ADRESS_NOTE VARCHAR2(1) 
  ,CODE             VARCHAR2(1) 
  ,EXP_PHONE1       VARCHAR2(1) 
  ,EXP_PHONE2       VARCHAR2(1) 
  ,DEST_PHONE1      VARCHAR2(1) 
  ,DEST_PHONE2      VARCHAR2(1) 
  ,CONTENT          VARCHAR2(1) 
  ,NOTES            VARCHAR2(1) 
  ,PACKAGE_COUNT    NUMBER(1) 
  ,WEIGHT_NET       NUMBER(1) 
  ,WEIGHT_BRUT      NUMBER(1) 
  ,VOL_NET          NUMBER(1) 
  ,VOL_BRUT         NUMBER(1) 
);
ALTER TABLE X_IMP_PARCEL ADD CONSTRAINT PK_XIMPPARCEL PRIMARY KEY (ID);

prompt Creating table X_IMP_UI_DC...

CREATE TABLE X_IMP_UI_DC (
   CODE        VARCHAR2(1) 
  ,NAME        VARCHAR2(1) 
  ,IS_STANDARD CHAR(1)
);

prompt Creating table X_IMP_UI_DC_FIELD...

CREATE TABLE X_IMP_UI_DC_FIELD (
   UIDC_CODE   VARCHAR2(1) 
  ,NAME        VARCHAR2(1) 
  ,DESCRIPTION VARCHAR2(1) 
);

prompt Creating table X_IMP_UI_GUI...

CREATE TABLE X_IMP_UI_GUI (
   CODE        VARCHAR2(1) 
  ,NAME        VARCHAR2(1) 
  ,IS_STANDARD CHAR(1)
);

