prompt Creating view V_INVOICE_HEADER...
@@V_INVOICE_HEADER.sql;
prompt Creating view V_INVOICE_ITEM...
@@V_INVOICE_ITEM.sql;
prompt Creating view V_LEDGER...
@@V_LEDGER.sql;
prompt Creating view V_STOCKS...
@@V_STOCKS.sql;
prompt Creating view V_ORCL_SESSION...
@@V_ORCL_SESSION.sql;
