prompt Creating trigger IINVOICE_BU...
@@IINVOICE_BU.sql;
prompt Creating trigger CURRENCY_BI...
@@CURRENCY_BI.sql;
prompt Creating trigger BANK_BI...
@@BANK_BI.sql;
prompt Creating trigger BANK_AGENCY_BI...
@@BANK_AGENCY_BI.sql;
prompt Creating trigger BILLING_CYCLE_BI...
@@BILLING_CYCLE_BI.sql;
prompt Creating trigger BPARTNER_BI...
@@BPARTNER_BI.sql;
prompt Creating trigger BP_ADRESS_BI...
@@BP_ADRESS_BI.sql;
prompt Creating trigger BP_BANKACCOUNT_BI...
@@BP_BANKACCOUNT_BI.sql;
prompt Creating trigger BP_CONTRACT_BI...
@@BP_CONTRACT_BI.sql;
prompt Creating trigger BP_SUBSCRIPTION_BI...
@@BP_SUBSCRIPTION_BI.sql;
prompt Creating trigger CITY_BI...
@@CITY_BI.sql;
prompt Creating trigger CLIENT_BI...
@@CLIENT_BI.sql;
prompt Creating trigger CREDIT_CLASS_BI...
@@CREDIT_CLASS_BI.sql;
prompt Creating trigger COUNTRY_BI...
@@COUNTRY_BI.sql;
prompt Creating trigger CURRENCY_XRATE_BI...
@@CURRENCY_XRATE_BI.sql;
prompt Creating trigger INV_DOC_TYPE_BI...
@@INV_DOC_TYPE_BI.sql;
prompt Creating trigger PERSON_BI...
@@PERSON_BI.sql;
prompt Creating trigger REGION_BI...
@@REGION_BI.sql;
prompt Creating trigger REPORTING_PERIOD_BI...
@@REPORTING_PERIOD_BI.sql;
prompt Creating trigger STREET_BI...
@@STREET_BI.sql;
prompt Creating trigger UOM_BI...
@@UOM_BI.sql;
prompt Creating trigger UOM_CONVERSION_BI...
@@UOM_CONVERSION_BI.sql;
prompt Creating trigger UOM_TYPE_BI...
@@UOM_TYPE_BI.sql;
prompt Creating trigger MENUITEM_BI...
@@MENUITEM_BI.sql;
prompt Creating trigger MENUITEM_TRL_BI...
@@MENUITEM_TRL_BI.sql;
prompt Creating trigger MENUITEM_TRL_BU...
@@MENUITEM_TRL_BU.sql;
prompt Creating trigger MENUITEM_AI...
@@MENUITEM_AI.sql;
prompt Creating trigger IINVOICE_BI...
@@IINVOICE_BI.sql;
prompt Creating trigger IINVOICE_ITEM_BI...
@@IINVOICE_ITEM_BI.sql;
prompt Creating trigger RINVOICE_BI...
@@RINVOICE_BI.sql;
prompt Creating trigger RINVOICE_ITEM_BI...
@@RINVOICE_ITEM_BI.sql;
prompt Creating trigger SYS_USER_BI...
@@SYS_USER_BI.sql;
prompt Creating trigger UI_GUI_BU...
@@UI_GUI_BU.sql;
prompt Creating trigger PAYMENT_DOC_TYPE_BI...
@@PAYMENT_DOC_TYPE_BI.sql;
prompt Creating trigger PAYMENT_BI...
@@PAYMENT_BI.sql;
prompt Creating trigger UI_DC_BI...
@@UI_DC_BI.sql;
prompt Creating trigger UI_DICTIONARY_BI...
@@UI_DICTIONARY_BI.sql;
prompt Creating trigger UI_DICTIONARY_TRL_BI...
@@UI_DICTIONARY_TRL_BI.sql;
prompt Creating trigger UI_DICTIONARY_AI...
@@UI_DICTIONARY_AI.sql;
prompt Creating trigger MENU_SHORTCUT_BI...
@@MENU_SHORTCUT_BI.sql;
prompt Creating trigger MENU_SHORTCUT_BU...
@@MENU_SHORTCUT_BU.sql;
prompt Creating trigger UI_DC_FIELD_INITVAL_BI...
@@UI_DC_FIELD_INITVAL_BI.sql;
prompt Creating trigger UI_GUI_BI...
@@UI_GUI_BI.sql;
prompt Creating trigger DELIVERY_AGENT_BI...
@@DELIVERY_AGENT_BI.sql;
prompt Creating trigger TASKS_BI...
@@TASKS_BI.sql;
prompt Creating trigger PAYMENT_BU...
@@PAYMENT_BU.sql;
prompt Creating trigger RINVOICE_BU...
@@RINVOICE_BU.sql;
prompt Creating trigger RINVOICE_ITEM_BU...
@@RINVOICE_ITEM_BU.sql;
prompt Creating trigger MENUITEM_BU...
@@MENUITEM_BU.sql;
prompt Creating trigger UI_DC_FIELD_BI...
@@UI_DC_FIELD_BI.sql;
prompt Creating trigger UI_DC_FIELD_BU...
@@UI_DC_FIELD_BU.sql;
prompt Creating trigger PROJECT_BI...
@@PROJECT_BI.sql;
prompt Creating trigger PROJECT_BU...
@@PROJECT_BU.sql;
prompt Creating trigger PROJECT_ISSUE_BI...
@@PROJECT_ISSUE_BI.sql;
prompt Creating trigger PROJECT_ISSUE_BU...
@@PROJECT_ISSUE_BU.sql;
prompt Creating trigger PROJECT_ISSUE_ATTACHMENT_BI...
@@PROJECT_ISSUE_ATTACHMENT_BI.sql;
prompt Creating trigger PROJECT_ISSUE_NOTE_BI...
@@PROJECT_ISSUE_NOTE_BI.sql;
prompt Creating trigger PROJECT_ISSUE_NOTE_BU...
@@PROJECT_ISSUE_NOTE_BU.sql;
prompt Creating trigger PROJECT_ISSUE_PRIORITY_BI...
@@PROJECT_ISSUE_PRIORITY_BI.sql;
prompt Creating trigger PROJECT_ISSUE_SEVERITY_BI...
@@PROJECT_ISSUE_SEVERITY_BI.sql;
prompt Creating trigger PROJECT_ISSUE_STATUS_BI...
@@PROJECT_ISSUE_STATUS_BI.sql;
prompt Creating trigger PROJECT_ISSUE_TYPE_BI...
@@PROJECT_ISSUE_TYPE_BI.sql;
prompt Creating trigger PROJECT_STATUS_BI...
@@PROJECT_STATUS_BI.sql;
prompt Creating trigger PROJECT_CMP_TYPE_BI...
@@PROJECT_CMP_TYPE_BI.sql;
prompt Creating trigger PROJECT_TYPE_BI...
@@PROJECT_TYPE_BI.sql;
prompt Creating trigger TIMESHEET_BI...
@@TIMESHEET_BI.sql;
prompt Creating trigger TIMESHEET_BU...
@@TIMESHEET_BU.sql;
prompt Creating trigger BP_CONTACT_BI...
@@BP_CONTACT_BI.sql;
prompt Creating trigger BP_CONTACT_BU...
@@BP_CONTACT_BU.sql;
prompt Creating trigger BP_PHONE_BI...
@@BP_PHONE_BI.sql;
prompt Creating trigger BP_PHONE_BU...
@@BP_PHONE_BU.sql;
prompt Creating trigger ASSET_BI...
@@ASSET_BI.sql;
prompt Creating trigger ASSET_BU...
@@ASSET_BU.sql;
prompt Creating trigger ASSET_GROUP_BI...
@@ASSET_GROUP_BI.sql;
prompt Creating trigger ASSET_GROUP_BU...
@@ASSET_GROUP_BU.sql;
prompt Creating trigger IINVOICE_ITEM_AU...
@@IINVOICE_ITEM_AU.sql;
prompt Creating trigger IINVOICE_ITEM_AI...
@@IINVOICE_ITEM_AI.sql;
prompt Creating trigger SALES_ORDER_BI...
@@SALES_ORDER_BI.sql;
prompt Creating trigger SALES_ORDER_BU...
@@SALES_ORDER_BU.sql;
prompt Creating trigger SERVER_MESSAGE_BI...
@@SERVER_MESSAGE_BI.sql;
prompt Creating trigger SERVER_MESSAGE_TRL_BI...
@@SERVER_MESSAGE_TRL_BI.sql;
prompt Creating trigger SERVER_MESSAGE_TRL_BU...
@@SERVER_MESSAGE_TRL_BU.sql;
prompt Creating trigger SALES_ORDER_LINE_BI...
@@SALES_ORDER_LINE_BI.sql;
prompt Creating trigger SALES_ORDER_LINE_BU...
@@SALES_ORDER_LINE_BU.sql;
prompt Creating trigger SERVER_MESSAGE_AI...
@@SERVER_MESSAGE_AI.sql;
prompt Creating trigger IINVOICE_ITEM_BU...
@@IINVOICE_ITEM_BU.sql;
prompt Creating trigger PURCHASE_ORDER_BI...
@@PURCHASE_ORDER_BI.sql;
prompt Creating trigger SYS_PARAM_BI...
@@SYS_PARAM_BI.sql;
prompt Creating trigger SYS_PARAM_BU...
@@SYS_PARAM_BU.sql;
prompt Creating trigger SYS_PARAM_VALID_VALUE_BI...
@@SYS_PARAM_VALID_VALUE_BI.sql;
prompt Creating trigger SYS_PARAM_VALUE_BI...
@@SYS_PARAM_VALUE_BI.sql;
prompt Creating trigger SYS_PARAM_VALUE_BU...
@@SYS_PARAM_VALUE_BU.sql;
prompt Creating trigger PURCHASE_ORDER_BU...
@@PURCHASE_ORDER_BU.sql;
prompt Creating trigger PURCHASE_ORDER_LINE_BI...
@@PURCHASE_ORDER_LINE_BI.sql;
prompt Creating trigger PURCHASE_ORDER_LINE_BU...
@@PURCHASE_ORDER_LINE_BU.sql;
prompt Creating trigger SYS_ROLE_BI...
@@SYS_ROLE_BI.sql;
prompt Creating trigger SYS_ROLE_BU...
@@SYS_ROLE_BU.sql;
prompt Creating trigger TEST_BI...
@@TEST_BI.sql;
prompt Creating trigger SYS_USER_BU...
@@SYS_USER_BU.sql;
prompt Creating trigger SYS_USER_ROLE_BI...
@@SYS_USER_ROLE_BI.sql;
prompt Creating trigger SYS_USER_LOGIN_BI...
@@SYS_USER_LOGIN_BI.sql;
prompt Creating trigger MENUBAR_BI...
@@MENUBAR_BI.sql;
prompt Creating trigger UI_DC_ROLE_PERMISSION_BI...
@@UI_DC_ROLE_PERMISSION_BI.sql;
prompt Creating trigger UI_DC_ROLE_PERMISSION_BU...
@@UI_DC_ROLE_PERMISSION_BU.sql;
prompt Creating trigger MENUITEM_ROLE_BI...
@@MENUITEM_ROLE_BI.sql;
prompt Creating trigger MENUITEM_ROLE_BU...
@@MENUITEM_ROLE_BU.sql;
prompt Creating trigger MM_STOCK_LOC_BI...
@@MM_STOCK_LOC_BI.sql;
prompt Creating trigger MM_ORG_INV_BI...
@@MM_ORG_INV_BI.sql;
prompt Creating trigger MM_ORG_INV_BU...
@@MM_ORG_INV_BU.sql;
prompt Creating trigger MM_ORG_INV_TYPE_BI...
@@MM_ORG_INV_TYPE_BI.sql;
prompt Creating trigger MM_ORG_INV_TYPE_BU...
@@MM_ORG_INV_TYPE_BU.sql;
prompt Creating trigger MM_STOCK_LOC_BU...
@@MM_STOCK_LOC_BU.sql;
prompt Creating trigger MM_PROD_STOCK_CMP_BI...
@@MM_PROD_STOCK_CMP_BI.sql;
prompt Creating trigger MM_STOCK_LOC_TYPE_BI...
@@MM_STOCK_LOC_TYPE_BI.sql;
prompt Creating trigger MM_STOCK_LOC_TYPE_BU...
@@MM_STOCK_LOC_TYPE_BU.sql;
prompt Creating trigger MM_MOVEMENT_IN_DOC_BI...
@@MM_MOVEMENT_IN_DOC_BI.sql;
prompt Creating trigger MM_MOVEMENT_IN_DOC_BU...
@@MM_MOVEMENT_IN_DOC_BU.sql;
prompt Creating trigger MM_MOVEMENT_IN_LINE_BI...
@@MM_MOVEMENT_IN_LINE_BI.sql;
prompt Creating trigger MM_MVMNTIN_DOCTYPE_BI...
@@MM_MVMNTIN_DOCTYPE_BI.sql;
prompt Creating trigger ORGANIZATION_BI...
@@ORGANIZATION_BI.sql;
prompt Creating trigger ORGANIZATION_BU...
@@ORGANIZATION_BU.sql;
prompt Creating trigger COST_CENTER_BI...
@@COST_CENTER_BI.sql;
prompt Creating trigger COST_CENTER_BU...
@@COST_CENTER_BU.sql;
prompt Creating trigger ORG_TYPE_BI...
@@ORG_TYPE_BI.sql;
prompt Creating trigger ORG_TYPE_BU...
@@ORG_TYPE_BU.sql;
prompt Creating trigger MM_PRODUCT_PRICE_BI...
@@MM_PRODUCT_PRICE_BI.sql;
prompt Creating trigger MM_PRODUCT_PRICE_BU...
@@MM_PRODUCT_PRICE_BU.sql;
prompt Creating trigger MM_PROD_ATTR_GRP_BI...
@@MM_PROD_ATTR_GRP_BI.sql;
prompt Creating trigger MM_PROD_ATTR_BI...
@@MM_PROD_ATTR_BI.sql;
prompt Creating trigger MM_PROD_ATTR_BU...
@@MM_PROD_ATTR_BU.sql;
prompt Creating trigger MM_PROD_ATTR_VAL_BI...
@@MM_PROD_ATTR_VAL_BI.sql;
prompt Creating trigger MM_PROD_ATTR_VAL_BU...
@@MM_PROD_ATTR_VAL_BU.sql;
prompt Creating trigger MM_PRODUCT_BI...
@@MM_PRODUCT_BI.sql;
prompt Creating trigger MM_PRODUCT_ACCOUNT_BI...
@@MM_PRODUCT_ACCOUNT_BI.sql;
prompt Creating trigger MM_PRODUCT_ACCOUNT_BU...
@@MM_PRODUCT_ACCOUNT_BU.sql;
prompt Creating trigger MM_PRODUCT_CATEGORY_BI...
@@MM_PRODUCT_CATEGORY_BI.sql;
prompt Creating trigger MM_PRODUCT_CATEGORY_ACCOUNT_BI...
@@MM_PRODUCT_CATEGORY_ACCOUNT_BI.sql;
prompt Creating trigger MM_PRODUCT_AI...
@@MM_PRODUCT_AI.sql;
prompt Creating trigger MM_PRODUCT_AU...
@@MM_PRODUCT_AU.sql;
prompt Creating trigger MM_PRICE_LIST_BI...
@@MM_PRICE_LIST_BI.sql;
prompt Creating trigger MM_PRICE_LIST_BU...
@@MM_PRICE_LIST_BU.sql;
prompt Creating trigger AC_ACCSCHEMA_BI...
@@AC_ACCSCHEMA_BI.sql;
prompt Creating trigger AC_ACCSCHEMA_BU...
@@AC_ACCSCHEMA_BU.sql;
prompt Creating trigger AC_ACCSCHEMA_PARAM_BI...
@@AC_ACCSCHEMA_PARAM_BI.sql;
prompt Creating trigger AC_ACCSCHEMA_PARAM_BU...
@@AC_ACCSCHEMA_PARAM_BU.sql;
prompt Creating trigger AC_ACCDOC_BI...
@@AC_ACCDOC_BI.sql;
prompt Creating trigger AC_ACCDOC_BU...
@@AC_ACCDOC_BU.sql;
prompt Creating trigger AC_ACCDOC_LINE_BI...
@@AC_ACCDOC_LINE_BI.sql;
prompt Creating trigger AC_ACCDOC_LINE_BU...
@@AC_ACCDOC_LINE_BU.sql;
prompt Creating trigger AC_ACCSCHEMA_ACCT_BI...
@@AC_ACCSCHEMA_ACCT_BI.sql;
prompt Creating trigger AC_ACCSCHEMA_ACCT_BU...
@@AC_ACCSCHEMA_ACCT_BU.sql;
prompt Creating trigger AC_ACCT_BI...
@@AC_ACCT_BI.sql;
prompt Creating trigger AC_ACCT_BU...
@@AC_ACCT_BU.sql;
prompt Creating trigger AC_ACCT_BALANCE_BI...
@@AC_ACCT_BALANCE_BI.sql;
prompt Creating trigger AC_ACCT_GRP_BI...
@@AC_ACCT_GRP_BI.sql;
prompt Creating trigger AC_ACCT_GRP_BU...
@@AC_ACCT_GRP_BU.sql;
prompt Creating trigger AC_ACCT_MOVEMENT_BI...
@@AC_ACCT_MOVEMENT_BI.sql;
prompt Creating trigger AC_ACC_JOURNAL_BI...
@@AC_ACC_JOURNAL_BI.sql;
prompt Creating trigger AC_ACC_JOURNAL_BU...
@@AC_ACC_JOURNAL_BU.sql;
prompt Creating trigger AC_ACC_PERIOD_BI...
@@AC_ACC_PERIOD_BI.sql;
prompt Creating trigger AC_ACC_PERIOD_BU...
@@AC_ACC_PERIOD_BU.sql;
prompt Creating trigger AC_ACC_YEAR_BI...
@@AC_ACC_YEAR_BI.sql;
prompt Creating trigger AC_ACC_YEAR_BU...
@@AC_ACC_YEAR_BU.sql;
prompt Creating trigger AC_CLIENT_ACCSCHEMA_BI...
@@AC_CLIENT_ACCSCHEMA_BI.sql;
prompt Creating trigger AC_CLIENT_ACCSCHEMA_BU...
@@AC_CLIENT_ACCSCHEMA_BU.sql;
prompt Creating trigger AC_ACC_YEAR_BD...
@@AC_ACC_YEAR_BD.sql;
prompt Creating trigger TR_PARCEL_BI...
@@TR_PARCEL_BI.sql;
prompt Creating trigger TR_TRANSPORT_STATUS_BI...
@@TR_TRANSPORT_STATUS_BI.sql;
prompt Creating trigger TR_TRANSPORT_STATUS_BU...
@@TR_TRANSPORT_STATUS_BU.sql;
prompt Creating trigger TR_TRANSPORT_TYPE_BI...
@@TR_TRANSPORT_TYPE_BI.sql;
prompt Creating trigger TR_TRANSPORT_TYPE_BU...
@@TR_TRANSPORT_TYPE_BU.sql;
prompt Creating trigger TR_TRANSPORT_BI...
@@TR_TRANSPORT_BI.sql;
prompt Creating trigger TR_TRANSPORT_BU...
@@TR_TRANSPORT_BU.sql;
prompt Creating trigger TR_VEHICLE_BI...
@@TR_VEHICLE_BI.sql;
prompt Creating trigger TR_VEHICLE_BU...
@@TR_VEHICLE_BU.sql;
prompt Creating trigger TR_VEHICLE_TYPE_BI...
@@TR_VEHICLE_TYPE_BI.sql;
prompt Creating trigger TR_VEHICLE_TYPE_BU...
@@TR_VEHICLE_TYPE_BU.sql;
prompt Creating trigger BP_ACCOUNT_BI...
@@BP_ACCOUNT_BI.sql;
prompt Creating trigger BP_ACCOUNT_BU...
@@BP_ACCOUNT_BU.sql;
prompt Creating trigger BP_CLIENT_BI...
@@BP_CLIENT_BI.sql;
prompt Creating trigger BP_CLIENT_BU...
@@BP_CLIENT_BU.sql;
prompt Creating trigger BP_CLIENT_AI...
@@BP_CLIENT_AI.sql;
prompt Creating trigger AC_CLIACCSCHEMA_PARAMVAL_BI...
@@AC_CLIACCSCHEMA_PARAMVAL_BI.sql;
prompt Creating trigger AC_CLIACCSCHEMA_PARAMVAL_BU...
@@AC_CLIACCSCHEMA_PARAMVAL_BU.sql;
prompt Creating trigger AC_CLIACCSCHEMA_PARAMACCT_BI...
@@AC_CLIACCSCHEMA_PARAMACCT_BI.sql;
prompt Creating trigger AC_CLIACCSCHEMA_PARAMACCT_BU...
@@AC_CLIACCSCHEMA_PARAMACCT_BU.sql;
prompt Creating trigger MM_PRODUCT_CLIENT_BI...
@@MM_PRODUCT_CLIENT_BI.sql;
prompt Creating trigger MM_PRODUCT_CLIENT_BU...
@@MM_PRODUCT_CLIENT_BU.sql;
prompt Creating trigger MM_PRODUCT_CLIENT_AI...
@@MM_PRODUCT_CLIENT_AI.sql;
