prompt Creating check constraint CHK_ACCPERIOD_CLOSED...                                                                                                                                                
alter table AC_ACC_PERIOD add constraint CHK_ACCPERIOD_CLOSED check (CLOSED IN ('Y','N'));                                                                                                              
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_ACCPERIOD_OPENED...                                                                                                                                                
alter table AC_ACC_PERIOD add constraint CHK_ACCPERIOD_OPENED check (OPENED IN ('Y','N'));                                                                                                              
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_ACCYEAR_CLOSED...                                                                                                                                                  
alter table AC_ACC_YEAR add constraint CHK_ACCYEAR_CLOSED check (CLOSED IN ('Y','N'));                                                                                                                  
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_ACCYEAR_ISFIRST...                                                                                                                                                 
alter table AC_ACC_YEAR add constraint CHK_ACCYEAR_ISFIRST check (IS_FIRST_YEAR IN ('Y','N'));                                                                                                          
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_ACCYEAR_OPENED...                                                                                                                                                  
alter table AC_ACC_YEAR add constraint CHK_ACCYEAR_OPENED check (OPENED IN ('Y','N'));                                                                                                                  
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_CLIENT_DEFAULT_CLIENT...                                                                                                                                           
alter table CLIENT add constraint CHK_CLIENT_DEFAULT_CLIENT check (DEFAULT_CLIENT IN ('Y','N'));                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_DATATYP_HAS_LENGTH...                                                                                                                                              
alter table APP_DATA_TYPE add constraint CHK_DATATYP_HAS_LENGTH check (HAS_LENGTH IN ('Y','N'));                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_DATATYP_HAS_PRECISION...                                                                                                                                           
alter table APP_DATA_TYPE add constraint CHK_DATATYP_HAS_PRECISION check (HAS_PRECISION IN ('Y','N'));                                                                                                  
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_DATATYP_IS_DEFAULT...                                                                                                                                              
alter table APP_DATA_TYPE add constraint CHK_DATATYP_IS_DEFAULT check (IS_DEFAULT IN ('Y','N'));                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_DEFIMPSTGFLDPROP_ACTIVE...                                                                                                                                         
alter table IE_DEF_IMPSTGFLD_PROP add constraint CHK_DEFIMPSTGFLDPROP_ACTIVE check (ACTIVE IN ('Y','N'));                                                                                               
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_DEFIMPSTGPROP_ACTIVE...                                                                                                                                            
alter table IE_DEF_IMPSTG_PROP add constraint CHK_DEFIMPSTGPROP_ACTIVE check (ACTIVE IN ('Y','N'));                                                                                                     
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_IMPSTGFLD_IN_DEST...                                                                                                                                               
alter table IE_IMP_STRATEGY_FIELD add constraint CHK_IMPSTGFLD_IN_DEST check (IN_DEST IN ('Y','N'));                                                                                                    
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_IMPSTGFLD_IN_SRC...                                                                                                                                                
alter table IE_IMP_STRATEGY_FIELD add constraint CHK_IMPSTGFLD_IN_SRC check (IN_SRC IN ('Y','N'));                                                                                                      
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_IMPSTGGRP_ACTIVE...                                                                                                                                                
alter table IE_IMP_STRATEGY_GROUP add constraint CHK_IMPSTGGRP_ACTIVE check (ACTIVE IN ('Y','N'));                                                                                                      
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_IMPSTG_ACTIVE...                                                                                                                                                   
alter table IE_IMP_STRATEGY add constraint CHK_IMPSTG_ACTIVE check (ACTIVE IN ('Y','N'));                                                                                                               
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_IMPSTG_FILE_TYPE...                                                                                                                                                
alter table IE_IMP_STRATEGY add constraint CHK_IMPSTG_FILE_TYPE check (FILE_TYPE IN ('xml','csv'));                                                                                                     
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_LANG_ACTIVE...                                                                                                                                                     
alter table LANGUAGES add constraint CHK_LANG_ACTIVE check (ACTIVE IN ('Y','N'));                                                                                                                       
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_MENUBAR_IS_DEFAULT...                                                                                                                                              
alter table MENUBAR add constraint CHK_MENUBAR_IS_DEFAULT check (IS_DEFAULT IN ('Y','N'));                                                                                                              
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_MENUBAR_IS_MODULE...                                                                                                                                               
alter table MENUBAR add constraint CHK_MENUBAR_IS_MODULE check (IS_MODULE_MENUBAR IN ('Y','N'));                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_MENUITEM_ACTIVE...                                                                                                                                                 
alter table MENUITEM add constraint CHK_MENUITEM_ACTIVE check (ACTIVE IN ('Y','N'));                                                                                                                    
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_ORGTYP_ACTIVE...                                                                                                                                                   
alter table ORG_TYPE add constraint CHK_ORGTYP_ACTIVE check (ACTIVE IN ('Y','N'));                                                                                                                      
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_PARCELREJRES_ACTIVE...                                                                                                                                             
alter table TR_PARCEL_REJECT_REASON add constraint CHK_PARCELREJRES_ACTIVE check (ACTIVE IN ('Y','N'));                                                                                                 
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_PARCEL_DELIVERED...                                                                                                                                                
alter table TR_PARCEL add constraint CHK_PARCEL_DELIVERED check (DELIVERED IN ('Y','N'));                                                                                                               
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_PARCEL_PICKEDUP...                                                                                                                                                 
alter table TR_PARCEL add constraint CHK_PARCEL_PICKEDUP check (PICKEDUP IN ('Y','N'));                                                                                                                 
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_PARCEL_REJECTED...                                                                                                                                                 
alter table TR_PARCEL add constraint CHK_PARCEL_REJECTED check (REJECTED IN ('Y','N'));                                                                                                                 
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_PAYDOCTYPE_COMP...                                                                                                                                                 
alter table PAYMENT_DOC_TYPE add constraint CHK_PAYDOCTYPE_COMP check (COMPENSATION IN ('Y','N'));                                                                                                      
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_PAYDOCTYPE_PAYABLE...                                                                                                                                              
alter table PAYMENT_DOC_TYPE add constraint CHK_PAYDOCTYPE_PAYABLE check (PAYABLE IN ('Y','N'));                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_PAYDOCTYPE_RECEIVABLE...                                                                                                                                           
alter table PAYMENT_DOC_TYPE add constraint CHK_PAYDOCTYPE_RECEIVABLE check (RECEIVABLE IN ('Y','N'));                                                                                                  
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_PAYMENT_IS_MULTI_PAYMENT...                                                                                                                                        
alter table PAYMENT add constraint CHK_PAYMENT_IS_MULTI_PAYMENT check (IS_MULTI_PAYMENT IN ('Y','N'));                                                                                                  
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_PAYMENT_IS_PAYABLE...                                                                                                                                              
alter table PAYMENT add constraint CHK_PAYMENT_IS_PAYABLE check (IS_PAYABLE IN ('Y','N'));                                                                                                              
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_PAYMENT_IS_PREPAYMENT...                                                                                                                                           
alter table PAYMENT add constraint CHK_PAYMENT_IS_PREPAYMENT check (IS_PREPAYMENT IN ('Y','N'));                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_PAYMENT_IS_RECEIVABLE...                                                                                                                                           
alter table PAYMENT add constraint CHK_PAYMENT_IS_RECEIVABLE check (IS_RECEIVABLE IN ('Y','N'));                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_PRICELVL_IS_DEFAULT...                                                                                                                                             
alter table MM_PRICE_LEVEL add constraint CHK_PRICELVL_IS_DEFAULT check (IS_DEFAULT IN ('Y','N'));                                                                                                      
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_PRJISSUE_IS_CLOSED...                                                                                                                                              
alter table PROJECT_ISSUE add constraint CHK_PRJISSUE_IS_CLOSED check (IS_CLOSED IN ('Y','N'));                                                                                                         
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_RINVDOCTYPE_ACTIVE...                                                                                                                                              
alter table RINV_DOC_TYPE add constraint CHK_RINVDOCTYPE_ACTIVE check (ACTIVE IN ('Y','N'));                                                                                                            
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_TASK_CLOSED...                                                                                                                                                     
alter table TASKS add constraint CHK_TASK_CLOSED check (CLOSED IN ('Y','N'));                                                                                                                           
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_TRANSPSTAT_ACTIVE...                                                                                                                                               
alter table TR_TRANSPORT_STATUS add constraint CHK_TRANSPSTAT_ACTIVE check (ACTIVE IN ('Y','N'));                                                                                                       
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_TRANSPTYPE_ACTIVE...                                                                                                                                               
alter table TR_TRANSPORT_TYPE add constraint CHK_TRANSPTYPE_ACTIVE check (ACTIVE IN ('Y','N'));                                                                                                         
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_UIDCROLEPRMS_DELETE...                                                                                                                                             
alter table UI_DC_ROLE_PERMISSION add constraint CHK_UIDCROLEPRMS_DELETE check (DELETE_ALLOWED IN ('Y','N'));                                                                                           
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_UIDCROLEPRMS_FETCH...                                                                                                                                              
alter table UI_DC_ROLE_PERMISSION add constraint CHK_UIDCROLEPRMS_FETCH check (FETCH_ALLOWED IN ('Y','N'));                                                                                             
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_UIDCROLEPRMS_INSERT...                                                                                                                                             
alter table UI_DC_ROLE_PERMISSION add constraint CHK_UIDCROLEPRMS_INSERT check (INSERT_ALLOWED IN ('Y','N'));                                                                                           
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_UIDCROLEPRMS_UPDATE...                                                                                                                                             
alter table UI_DC_ROLE_PERMISSION add constraint CHK_UIDCROLEPRMS_UPDATE check (UPDATE_ALLOWED IN ('Y','N'));                                                                                           
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_UIDC_DEPRECATED...                                                                                                                                                 
alter table UI_DC add constraint CHK_UIDC_DEPRECATED check (DEPRECATED IN ('Y','N'));                                                                                                                   
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_UIDC_NBS_STANDARD...                                                                                                                                               
alter table UI_DC add constraint CHK_UIDC_NBS_STANDARD check (NBS_STANDARD IN ('Y','N'));                                                                                                               
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_UIDC_USER_BUILD...                                                                                                                                                 
alter table UI_DC add constraint CHK_UIDC_USER_BUILD check (USER_BUILD IN ('Y','N'));                                                                                                                   
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_UIFLDINITVAL_ACTIVE...                                                                                                                                             
alter table UI_DC_FIELD_INITVAL add constraint CHK_UIFLDINITVAL_ACTIVE check (ACTIVE IN ('Y','N'));                                                                                                     
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_UIGUI_DEPRECATED...                                                                                                                                                
alter table UI_GUI add constraint CHK_UIGUI_DEPRECATED check (DEPRECATED IN ('Y','N'));                                                                                                                 
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_UIGUI_NBS_STANDARD...                                                                                                                                              
alter table UI_GUI add constraint CHK_UIGUI_NBS_STANDARD check (NBS_STANDARD IN ('Y','N'));                                                                                                             
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_UIGUI_USER_BUILD...                                                                                                                                                
alter table UI_GUI add constraint CHK_UIGUI_USER_BUILD check (USER_BUILD IN ('Y','N'));                                                                                                                 
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_UILOV_NBS_DEPRECATED...                                                                                                                                            
alter table UI_LOV add constraint CHK_UILOV_NBS_DEPRECATED check (DEPRECATED IN ('Y','N'));                                                                                                             
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_UILOV_NBS_STANDARD...                                                                                                                                              
alter table UI_LOV add constraint CHK_UILOV_NBS_STANDARD check (NBS_STANDARD IN ('Y','N'));                                                                                                             
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_UILOV_NBS_USER_BUILD...                                                                                                                                            
alter table UI_LOV add constraint CHK_UILOV_NBS_USER_BUILD check (USER_BUILD IN ('Y','N'));                                                                                                             
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_USER_ACCOUNT_EXPIRED...                                                                                                                                            
alter table SYS_USER add constraint CHK_USER_ACCOUNT_EXPIRED check (ACCOUNT_EXPIRED IN ('Y','N'));                                                                                                      
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_USER_ACCOUNT_LOCKED...                                                                                                                                             
alter table SYS_USER add constraint CHK_USER_ACCOUNT_LOCKED check (ACCOUNT_LOCKED IN ('Y','N'));                                                                                                        
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CHK_VEHICLETYP_ACTIVE...                                                                                                                                               
alter table TR_VEHICLE_TYPE add constraint CHK_VEHICLETYP_ACTIVE check (ACTIVE IN ('Y','N'));                                                                                                           
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CK_ACCOUNT_SUMMARY...                                                                                                                                                  
alter table AC_ACCT add constraint CK_ACCOUNT_SUMMARY check (SUMMARY IN ('N','Y'));                                                                                                                     
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CK_CONTRSTAT_ACTIVE...                                                                                                                                                 
alter table CONTRACT_STATUS add constraint CK_CONTRSTAT_ACTIVE check (ACTIVE IN ('Y','N'));                                                                                                             
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CK_COUNTRY_ACTIVE...                                                                                                                                                   
alter table COUNTRY add constraint CK_COUNTRY_ACTIVE check (ACTIVE IN ('N','Y'));                                                                                                                       
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CK_CURRENCY_ACTIVE...                                                                                                                                                  
alter table CURRENCY add constraint CK_CURRENCY_ACTIVE check (ACTIVE IN ('N','Y'));                                                                                                                     
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CK_PRODCATEGACC_ACTIVE...                                                                                                                                              
alter table MM_PRODUCT_CATEGORY_ACCOUNT add constraint CK_PRODCATEGACC_ACTIVE check (ACTIVE IN ('N','Y'));                                                                                              
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CK_PRODCATEG_ACTIVE...                                                                                                                                                 
alter table MM_PRODUCT_CATEGORY add constraint CK_PRODCATEG_ACTIVE check (ACTIVE IN ('Y','N'));                                                                                                         
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CK_PROD_STORABLE...                                                                                                                                                    
alter table MM_PRODUCT add constraint CK_PROD_STORABLE check (STORABLE IN ('Y','N'));                                                                                                                   
                                                                                                                                                                                                        
                                                                                                                                                                                                        
prompt Creating check constraint CK_PROD_SUMMARY...                                                                                                                                                     
alter table MM_PRODUCT add constraint CK_PROD_SUMMARY check (SUMMARY IN ('Y','N'));                                                                                                                     
                                                                                                                                                                                                        
                                                                                                                                                                                                        
